### ISSUE TITLE
Set up tagging on Docker Hub Automated Builds so consumers can version lock

### ISSUE THREAD

**Issue by orospakr** [itzg/dockerfiles#100]
I'm a big believer in repeatable builds/deploys, and so it would be amazing if the automated builds on docker hub were tagged with some regular version numbering (https://docs.docker.com/docker-hub/builds/ talks about how to do it; it can use git tags for example, matched with a regex and passed through into Docker tags).

This is particularly important in Kubernetes environments, where something as innocuous as an automatic node restart or scaling change could (would) cause unexpected divergence of the running versions of these images on some subset of the cluster's nodes (on account of image downloads occurring just-in-time when a task is scheduled on a Kube node).  With version tags, users will be able to properly do rolling-releases on their clusters of new versions of the images without being surprised.

Thank you :)

**Comment by itzg** [comment]
I definitely agree. I have created a small mess for myself by originally lumping all my images into one Github repo...however, tagging and labeling is still quite doable. 

What particular images would you like to see tagged first?

**Comment by itzg** [comment]
I have been tagging and branching the more recent versions, so as an example the following are available at this time:

```
2.3.4
2.4.0
2.4.1
2.x
2.4.x
latest
5.0.x
2.3.x
1.3
1.4
1.x
```

from https://hub.docker.com/r/itzg/elasticsearch/tags/
