### ISSUE TITLE
Have chown be smart in start.sh

### ISSUE THREAD

**Issue by jmiahman** [itzg/dockerfiles#104]
The time it takes to chown a data folder can be quite long with regards to starting with existing installs, and ever worse over things like mounted nfs volumes. Maybe check the uid and gid and see if the chown is even needed and not run it if not, or just have a way to turn it off by a flag.

**Comment by itzg** [comment]
@jmiahman I have pushed a smarter :) version of the startup logic at image ID `sha256:694833030972a1d2343df8f9692c563e29f4b202d264aacfa8c71a26f2ad9a5c`

Can you try that out and confirm it's fixed appropriately?

**Comment by jmiahman** [comment]
I now get..
Correcting writability of /data ...
chown: cannot read directory ‘/data’: Permission denied

can there be a flag to just turn it off, I know the permissions are set correctly.

**Comment by itzg** [comment]
Yep, I'll just add a flag to disable. Stay tuned.

**Comment by itzg** [comment]
Image `sha256:0cd13c4449ee4c8e0bdf57fa508e89c895edad66d551433c55c7d31bf8d359ee` now has an option to skip that: 

    -e SKIP_OWNERSHIP_FIX=TRUE
