### ISSUE TITLE
 An unexpected error occurred while trying to open file minecraft_server.1.10.2.jar

### ISSUE THREAD

**Issue by Ashtonian** [itzg/dockerfiles#105]
```
=2016-09-15T23:38:04.768316183Z Switching to user 'minecraft'
=2016-09-15T23:38:04.774427899Z Checking version information.
:2016-09-15T23:38:04.853613962Z Checking type information.
L2016-09-15T23:38:04.935382875Z mmap failed for CEN and END part of zip file
L2016-09-15T23:38:04.945318914Z mmap failed for CEN and END part of zip file
y2016-09-15T23:38:04.947245344Z Error: An unexpected error occurred while trying to open file minecraft_server.1.10.2.jar
```

I'm wondering if this is a permissions issue? When I don't specify the parent data volume it works. I'm using the following to build it: 

```
docker run --restart=always -e 'JVM_OPTS=-Xmx27000M -Xms1024M' -e EULA=true -v /media/Lutece/Applications/MineCraft:/data  -d -p 25565:25565 --name mc itzg/minecraft-server
```

/media/Lutece is a mergerfs share and it has bunch of files in the minecraft folder.

**Comment by itzg** [comment]
Yes, I think you're right that it might be a permissions issue. The container runs the minecraft process with uid=1000, and gid=1000. I just found this little trick to view the ownership of a directory

    find /data -maxdepth 0 -printf "%U:%G\n"

so you could try the same with your host's path `/media/Lutece/Applications/MineCraft`. If the owner/group is different then you can pass `-e UID` and `-e GID` during `docker run` to adjust the IDs of the `minecraft` user within the container.

**Comment by Ashtonian** [comment]
So I think its the fact that it was a mergerfs mount. I can experiment a bit more. But i mapped the host drive directly and it worked...

**Comment by itzg** [comment]
That makes sense since there was mention of mmap in the error

**Comment by itzg** [comment]
Feel free to comment further or re-open if you bump into this.
