### ISSUE TITLE
Minecraft Gamemode

### ISSUE THREAD

**Issue by jkoan** [itzg/dockerfiles#107]
Hello,
in the case loop is a little Bug,
s* mode will mach survive and spactator mode  ;)
Probably it sould be su* and sp* to mach all cases :)

https://github.com/itzg/dockerfiles/blob/master/minecraft-server/start-minecraft.sh#L362

**Comment by itzg** [comment]
Good catch, thanks. I'll go with your suggestion :)

**Comment by itzg** [comment]
Pushed to Docker Hub at `sha256:c0fc7c7ae373d8d2f78f781628ab6b98b7b26622e7f8c5383593e9e9dd018406`
