### ISSUE TITLE
Provide an Elasticsearch 5.0 RC image

### ISSUE THREAD

**Issue by itzg** [itzg/dockerfiles#108]
As ES is nearing 5.0 GA, it'll be good to have an image to start developing against and trying out.

**Comment by ferronrsmith** [comment]
ES 5.0 GA has been released. Do you have a time-line for an updated image ?

**Comment by itzg** [comment]
I'm glad you pinged me on this. Especially since it's GA now, I'll focus on this within the next few days.

**Comment by itzg** [comment]
@ferronrsmith I have pushed changes and a built for 5.0.0 at image ID `5544d7222e22`. Since there were a few changes needed from 2.x to 5.x, can you please double check the image for me?

**Comment by ferronrsmith** [comment]
Sure ! Thanks for the fast turnaround

**Comment by ferronrsmith** [comment]
@itzg Ok I tested this. In different modes :

|mode|pass|
|-----------|-------|
|single node mode | :white_check_mark: |
|unicast cluster mode | :white_check_mark: |
|docker-compose with dedicated type | :x: | 

- 

Got the following error :

```log
escluster_gateway_1 exited with code 64
data_1     | starts elasticsearch
data_1     | 
data_1     | Option                Description                                              
data_1     | ------                -----------                                              
data_1     | -E <KeyValuePair>     Configure a setting                                      
data_1     | -V, --version         Prints elasticsearch version information and exits       
data_1     | -d, --daemonize       Starts Elasticsearch in the background                   
data_1     | -h, --help            show help                                                
data_1     | -p, --pidfile <Path>  Creates a pid file in the specified path on start        
data_1     | -q, --quiet           Turns off standard ouput/error streams logging in console
data_1     | -s, --silent          show minimal output                                      
data_1     | -v, --verbose         show verbose output                                      
data_1     | ERROR: node.master is not a recognized option

````

**Comment by itzg** [comment]
And thank you for the fast turnaround on the testing. I'll get right onto fixing that.

**Comment by itzg** [comment]
@ferronrsmith please try the latest that's pushed now, which is `2c1c11aa01ee`. There were some lingering use of the old parameter style. It looks like I also needed to fix the `MIN_MASTERS` option.

**Comment by ferronrsmith** [comment]
Ok nice. I will retest

**Comment by ferronrsmith** [comment]
|mode|pass|
|-----------|-------|
|single node mode | :white_check_mark: |
|unicast cluster mode | :white_check_mark: |
|docker-compose with dedicated type  | :white_check_mark: |

**Comment by itzg** [comment]
Execellent. Thanks so much for your help.
