### ISSUE TITLE
[minecraft-server] Run commands on the minecraft server from the Docker remote API

### ISSUE THREAD

**Issue by itzg** [itzg/dockerfiles#11]

**Comment by itzg** [comment]
Note to self (and throwing out there for discussion): rather than hand craft the `exec`'ing and such, it might be time to introduce [Supervisor](http://supervisord.org/) and use its `supervisorctl`.

I also did some experiments with `docker attach`'ing to the container process, but nothing positive on that front. The Ctrl-P -> Ctrl-Q to exit the attachment didn't even work.

**Comment by DanTheColoradan** [comment]
Love your docker image. Just wanted to say thanks and I'll be keeping an eye on this issue. This sounds like an awesome feature! :+1:

**Comment by DanTheColoradan** [comment]
Would Supervisor be implemented in conjunction with the Docker remote API?

I believe our goals is to run commands on the Minecraft server (which is in a docker container). One way of doing that would be to send it commands through the Docker remote API. I assume that's possible anyway ;-) Another option would be to run Supervisor, and then use the supervisorctl to run the commands.

Does that sound right?

**Comment by itzg** [comment]
Latest experiment (not remote yet) is looking better. It turns out the `-i` option when launching the container is what tells Docker to enable for interactive/input. Then, add `-t` to setup a pseudo-tty, so...

```
docker run -d -it --name mc-a -p 25567:25565 -e EULA=TRUE itzg/minecraft-server
docker attach mc-a
help
[00:37:04] [Server thread/INFO]: --- Showing help page 1 of 9 (/help <page>) ---
[00:37:04] [Server thread/INFO]: /achievement <give|take> <stat_name|*> [player]
[00:37:04] [Server thread/INFO]: /ban <name> [reason ...]
[00:37:04] [Server thread/INFO]: /ban-ip <address|name> [reason ...]
[00:37:04] [Server thread/INFO]: /banlist [ips|players]
[00:37:04] [Server thread/INFO]: /blockdata <x> <y> <z> <dataTag>
[00:37:04] [Server thread/INFO]: /clear [player] [item] [data] [maxCount] [dataTag]
[00:37:04] [Server thread/INFO]: /clone <x1> <y1> <z1> <x2> <y2> <z2> <x> <y> <z> [maskMode] [cloneMode]
^p^q
```

...and I'm out and can re-attach again.

Now I'm going to expand my experiment by starting my Docker daemon with `tcp` socket enabled via `-H tcp://0.0.0.0:2375`...

**Comment by itzg** [comment]
Remote attach experiment: :+1: 

So, I adjusted my Docker service config (`/etc/default/docker` on Ubuntu):

```
DOCKER_OPTS="\
 -H tcp://0.0.0.0:2375 "
```

and restarted the service and started back up that "mc-a" container I created above 

```
service docker restart
export DOCKER_HOST=localhost:2375
docker start mc-a
```

*Notice I had to now specify the `DOCKER_HOST` environment variable.*

Then, I hop on another Linux machine (a boot2docker VM in my case):

```
export DOCKER_HOST=192.168.0.100:2375
docker attach mc-a
...interact away...
^p^q
```

**Comment by DanTheColoradan** [comment]
We might consider noting something about:

[Securing Docker's Remote API](http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CB8QFjAA&url=http%3A%2F%2Fblog.james-carr.org%2F2013%2F10%2F30%2Fsecuring-dockers-remote-api%2F&ei=2FL6VO7JFo6ayASG4YG4DQ&usg=AFQjCNFEFpV8qeRNw1XbLOStNEtkIPqqoQ&bvm=bv.87611401,d.aWw)
[Running Docker with HTTPS](https://docs.docker.com/articles/https/)

**Comment by itzg** [comment]
Built and pushed with image ID e18a55eabebf
