### ISSUE TITLE
Personal Minecraft Server Hosting in One-Click with Jelastic

### ISSUE THREAD

**Issue by sych74** [itzg/dockerfiles#110]
Hi, we built an automation [deployment package for Jelastic cloud](https://github.com/jelastic-jps/minecraft-server) based on the docker image from this repo. More details can be found at this [blog post](http://blog.jelastic.com/2016/11/01/personal-minecraft-server-hosting-docker/). Any feedback for the further improvements will be highly appreciated.

**Comment by itzg** [comment]
This is an awesome use of the image. I'm going to definitely give it a try ASAP.

My efforts to do something vaguely similar backed by pre-1.12 Swarm is described [here](https://getcarina.com/blog/deploying-and-building-minecraft-as-a-service/). I still have [an instance running](https://mccy.itzg.me), but my work on [the code](https://github.com/moorkop/mccy-engine) has stalled out :(.

Feel free to log any issues that would help out any aspect of the Jelastic approach. Likewise, let me know if there's any bits/concepts of MCCY that you think I could contribute.

**Comment by sych74** [comment]
Thanks for sharing the links and for the feedback. 
Why have you added nginx in front? I do not have too much experience with minecraft server installation, so I did not get this point.
 
We just published the package and Jelastic public cloud providers will push/promote the package to end users soon. I hope after that we will get feedback from end users, I will definitely share it with you. Everything else looks good so far. 

Btw, your image was used by Jelastic and MSFT Azure folks during various demo presentations - live migration of running minecraft server in docker container from AWS to Azure. People liked it very much :). There is a [video example](https://www.youtube.com/watch?v=HfN4L6RFL10).  

Thanks again for your great job

**Comment by itzg** [comment]
ngnix is only in front of my MCCY web application to provide HTTPS termination. The Minecraft client-server communication is direct to each particular MC container.

That's so cool to hear about it being used for demos. I also came across it being used in a Rexray demo for persistent/multi-host volumes -- it's definitely more fun to demo a Minecraft world than a RDBS :)

You're very welcome.
