### ISSUE TITLE
Bump Logstash to 5.1.1

### ISSUE THREAD

**Issue by ferronrsmith** [itzg/dockerfiles#118]

**Comment by itzg** [comment]
Wow, the current `itzg/logstash` is way out of date. Bear with me since it may take longer to resuscitate this one.

**Comment by ferronrsmith** [comment]
Haha ok np

**Comment by itzg** [comment]
For this (and Kibana) I think I'm going to "deprecate" my images in favor of the official images, [logstash ](https://hub.docker.com/_/logstash/) and [kibana](https://hub.docker.com/_/kibana/). They have been working well for me, combined with `itzg/elasticsearch:5` and friends. 

@ferronrsmith , can you let me me know if the official image works for you (or perhaps that's what you're already using)?

**Comment by ferronrsmith** [comment]
Make sense

**Comment by itzg** [comment]
I'm tracking the deprecation in #130
