### ISSUE TITLE
Base image 'java' for Minecraft is deprecated in favor of 'openjdk'

### ISSUE THREAD

**Issue by mikesager** [itzg/dockerfiles#122]
FYI, per the Docker Hub description for the java base image:

> This image is officially deprecated in favor of the openjdk image, and will receive no further updates after 2016-12-31 (Dec 31, 2016). Please adjust your usage accordingly.

**Comment by itzg** [comment]
Thanks. I hadn't switched some of my other images but forgot to circle around for here.

**Comment by itzg** [comment]
Pushed to Hub at image ID `9ec4d889769f`
