### ISSUE TITLE
Minecraft FTB start issue

### ISSUE THREAD

**Issue by r1cebank** [itzg/dockerfiles#132]
Hi, thanks for this amazing docker image. But i am having some issue to start an ftb server.

Here is the command i used:
docker run -d -v xxxxx/mc:/data -e TYPE=FTB -e FTB_SERVER_MOD=FTBPresentsCrackpackServer_1.1.0.zip -p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server

When i checked the logs, i see this:

```
Switching to user 'minecraft'
Checking version information.
Checking type information.
Looking for Feed-The-Beast server modpack.
Unpacking FTB server modpack /data/FTBPresentsCrackpackServer_1.1.0.zip ...
unzip: unrecognized option: u
BusyBox v1.25.1 (2016-10-26 16:15:20 GMT) multi-call binary.

Usage: unzip [-lnopq] FILE[.zip] [FILE]... [-x FILE...] [-d DIR]

Extract FILEs from ZIP archive

	-l	List contents (with -q for short form)
	-n	Never overwrite files (default: ask)
	-o	Overwrite
	-p	Print to stdout
	-q	Quiet
	-x FILE	Exclude FILEs
	-d DIR	Extract into DIR
chmod: /data/FeedTheBeast/ServerStart.sh: No such file or directory
```

Any help will be greatly appreciated. Thanks

**Comment by itzg** [comment]
Thanks for reporting this. It seems to be due to switching to an Alpine base image, so it should be fairly straightforward to resolve.

**Comment by itzg** [comment]
@HenryGessau , regarding that question, I double checked that `unzip` without the `-u` will behave as expected in the case when a mod is upgraded from one version to another:

```
#!/bin/sh

cd /tmp
echo "one: initial" > one
zip /tmp/first.zip one

echo "one: updated" > one
echo "two: initial" > two
zip /tmp/second.zip one two

mkdir /tmp/out

unzip -o -d /tmp/out /tmp/first.zip
cat /tmp/out/one

unzip -o -d /tmp/out /tmp/second.zip
cat /tmp/out/one /tmp/out/two
```

**Comment by r1cebank** [comment]
I tried to add unzip to the `apk add` and it appears to be working.

+ unzip \

**Comment by itzg** [comment]
Apparently one of the other packages was already pulling in `unzip`. I'll have a change to try out shortly -- just wanted to recreate your scenario first.

**Comment by itzg** [comment]
Oh yeah, I keep forgetting with FTB to download the server flavor of file and not just the modpack :)

**Comment by itzg** [comment]
@r1cebank can you `docker pull itzg/minecraft-server` to pick up `688de9dbc7f0` and try that out?

**Comment by r1cebank** [comment]
It worked perfectly, thanks.
