### ISSUE TITLE
About minecraft remote issues

### ISSUE THREAD

**Issue by wiput1999** [itzg/dockerfiles#135]
Hi,
   I'm trying to execute command into minecraft container but I can't execute command. Is it possible to run command on it without RCON? Like Minecraft web panel can be execute command directly to minecraft server.

Thanks

**Comment by wiput1999** [comment]
No I want to run it daemon and make it able to use like docker exec <container> <command> like this with out RCON. Is it possible?

**Comment by wiput1999** [comment]
I'm talking about using Docker API to control it

**Comment by itzg** [comment]
I'm sorry, I misunderstood the original question. Yes, `docker exec` is the way to run a new process/command inside of the container's control space.

If you mean the low level Docker API, then yes, that can be done via this REST endpoint:
https://docs.docker.com/engine/api/v1.27/#tag/Exec

**Comment by wiput1999** [comment]
But why I can't run command into process?

**Comment by wiput1999** [comment]
I'm trying to use
`docker exec 88a034eebfe5 stop`
to run like stop minecraft server but it returns
`rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"stop\": executable file not found in $PATH"`

**Comment by itzg** [comment]
Thanks @wiput1999 , I was just about to ask what your actual goal was. OK, you definitely will need to be using `docker attach` since what you're needing to do is "send a command" to the minecraft-server process itself via its standard input.

The challenge is that the minecraft console expects a terminal (TTY), but when trying to programmatically stop the service it isn't working for me:
```
> docker run -it -d --name mc -e EULA=TRUE itzg/minecraft-server
e6a567122a77274da94d87a574cf894e333b84d155f6d566bfd095a34811ec36

> echo stop | docker attach mc
the input device is not a TTY
```

It looks like we need to research some google results from that "the input device is not a TTY" error.

**Comment by wiput1999** [comment]
```
import docker
client = docker.from_env()

container = client.containers.run('itzg/minecraft-server',ports={'25565/tcp': 25565, '25575/tcp': 25575},environment={"EULA": "TRUE", "VERSION": "1.11.2", "ENABLE_RCON" : "true", "RCON_PASSWORD" : "test" },detach=True,tty=True,name = "Minecraft")
```
On my code I think it has been enabled tty but they not work and I don't know why Minecraft console is not on top when I execute command into container

**Comment by wiput1999** [comment]
Wow I think I have found the way to execute command directly in to minecraft process by adding it into environment :D I see this man do it
https://github.com/dlord/minecraft-docker/blob/master/minecraft

**Comment by itzg** [comment]
Ah, so wrapping it in a `tmux` session does actually make sense. I'm very new to `tmux`, but I think I follow the technique there. Feel free to take a stab at this approach and submit a PR. The main spot to adjust is here https://github.com/itzg/dockerfiles/blob/master/minecraft-server/start-minecraft.sh#L504-L509

**Comment by itzg** [comment]
@wiput1999 since you're using python and already enabling rcon, perhaps this would work:

http://python-valve.readthedocs.io/en/latest/rcon.html

**Comment by itzg** [comment]
@wiput1999 as an alternative idea, I wrote a little rcon-cli application, where you can download a built binary from

https://github.com/itzg/rcon-cli/releases/tag/1.0

For example, on Mac OS I can do this to programmatically stop a minecraft server:

```
wget https://github.com/itzg/rcon-cli/releases/download/1.0/rcon-cli_darwin_amd64
chmod +x rcon-cli_darwin_amd64
echo stop | ./rcon-cli_darwin_amd64 --host localhost --port 25575 --password test
```

Later tonight I'll work this into the `itzg/minecraft-server` image as an alternate entrypoint command.

**Comment by itzg** [comment]
@wiput1999 I have now pushed an update that integrates the rcon-cli into the image:

https://github.com/itzg/dockerfiles/tree/master/minecraft-server#interacting-with-the-server

Can you try that out to see if it takes care of your scenario?

**Comment by wiput1999** [comment]
Oh! Thank you but I have build my own one now with tmux.
