### ISSUE TITLE
Minecraft-Server - incomplete UID and GID replacement in start script 

### ISSUE THREAD

**Issue by cheinig** [itzg/dockerfiles#136]
Minecraft-Server
The UID / GID replace operation in the start script is working wrong, because it tries to replace the value 1000 with the value provided in UID/GID on every start.

I set my UID and GID environment variables to 10008 and everything works fine on first startup.
If i stop the container and start it again, the script will try to replace the string 1000 again. Although it was already set to 10008 during the last start, the string 1000 is found again and will be replaced. 
This time with 100088. <- bug

Possible replace commands are:
sed -i "/^minecraft/s/:1000:1000:/:${UID}:${GID}:/g" /etc/passwd
sed -i "/^minecraft/s/:1000:/:${GID}:/g" /etc/group

**Comment by itzg** [comment]
Thanks @cheinig for reporting this and providing an elegant solution -- I am going to apply that as the fix for this.

**Comment by itzg** [comment]
The fix has now been pushed to Hub with image ID `3bd80685ad0b`
