### ISSUE TITLE
Add Python for RaspberryJamMod and others?

### ISSUE THREAD

**Issue by smxsm** [itzg/dockerfiles#148]
Hi, I really love your minecraft-server docker image! One suggestion: how about adding python packages, so that you can use e.g. a FORGE type server with e.g. the RaspberryJamMod (https://github.com/arpruss/raspberryjammod) to run python scripts in Minecraft?
I've tried it in my own image based on yours and it worked like a charm. All I've added was

`RUN apk --update add python2 python2-dev py-setuptools`

**Comment by itzg** [comment]
That's like a good feature. I'll just double check that it doesn't grow the image size too much.

**Comment by smxsm** [comment]
Cool :) Here are the image sizes I got when adding python in my derived image after adding the three packages:
![image](https://cloud.githubusercontent.com/assets/1737182/25790548/d9813d3c-33b9-11e7-9cf8-dda96b15fc47.png)

**Comment by itzg** [comment]
@smxsm can you try out the latest image I pushed? apk was acting a little odd for me, so I ended up adding `python` and `python-dev`; however, I was able to run some of the RaspberryJamMod sample scripts.

**Comment by smxsm** [comment]
Works perfectly, thank you very much for adding! 👍

**Comment by itzg** [comment]
Awesome, thanks. 

I'll leave this issue open to track merging the same to the Debian branch.

**Comment by itzg** [comment]
...and added for debian tag: https://hub.docker.com/r/itzg/minecraft-server/builds/bkpt8b6rkkvumvuacnrdpyi/
