### ISSUE TITLE
Server doen't init with some environment variable settings

### ISSUE THREAD

**Issue by dblM90** [itzg/dockerfiles#151]
Hi there,

im trying to run a Feed-The-Beast Server, but it seems, that some environments variables are not loaded on init, such as MAX_PLAYERS, WHITELIST, OPS, MOTD,... 

Maybe we could investigate this issue.

Best regards

**Comment by itzg** [comment]
The FTB support is a newer contribution, so I have to admit I'm not as familiar with it. My suspicion, without looking, is that the docker entry script is designed for tweaking the "normal" server config properties. Those tweaks might go to waste since FTB has its additional entry script.

**Comment by dblM90** [comment]
It might be that FTB overrides the settings while installation process. I don't know how to fix it. For now, i edited the settings manually to get the configuration that i want to have.

**Comment by itzg** [comment]
@dblM90 I'm testing out some changes in a branch that seem to fix it. Can you also help test it out by pulling the image tag `ftb`, such as

```
docker run ... itzg/minecraft-server:ftb
```

I have also included an enhancement where you can have it download the server pack by passing a URL such as https://www.feed-the-beast.com/projects/ftb-infinity-lite-1-10/files/2402889 into `FTB_SERVER_MOD`.

**Comment by dblM90** [comment]
@itzg i will test it as soon as possible

**Comment by dblM90** [comment]
I've tried to run a Minecraft FTB Server (Beyond mod pack). It seems to do the right configuration except of setting whitelist and ops. The whitelist option is set to true, and a file with my username named whitelist.txt is generated. But there is another whitelist and a ops file in the feedthebeast folder, where it is not set.

**Comment by itzg** [comment]
I'm so glad you tested this out. Yep, you've discovered a couple more files I need to copy from the outer server directory to FTB.

**Comment by dblM90** [comment]
Could you please write me, if you have fixed it? I will test it on my server...

**Comment by itzg** [comment]
@dblM90, sorry for the delay. I should be able to wrap this up later today and get it pushed out.

**Comment by itzg** [comment]
The fix is being built/pushed via https://hub.docker.com/r/itzg/minecraft-server/builds/bbaregrhqpgeku3vykw8kki/
