### ISSUE TITLE
General Download URL for every Version/Type

### ISSUE THREAD

**Issue by Reviville** [itzg/dockerfiles#154]
Hey ho,

just a question and probably a new feature.

I was wondering if you could, instead of deviding the Download variables (SPIGOT_DOWNLOAD_URL, BUKKIT_DOWNLOAD_URL etc.), just implement one general DOWNLOAD_URL=...

If not, i would like to request a new download url for Forge... :p

Thank you :)

**Comment by itzg** [comment]
Since Forge requires an extra step to run its installer, it has to act a little different. As such, I can certainly add a `FORGE_INSTALLER_URL`.

**Comment by Reviville** [comment]
Would be awesome :)

**Comment by itzg** [comment]
@Reviville since you'd be providing the specific URL, I assume you don't care/need to specify the version particulars? Right now I have to do this dance to lookup the corresponding Forge version for a given Minecraft version.

**Comment by Reviville** [comment]
yeah ofc, i dont need that :p

**Comment by itzg** [comment]
Excellent.

Also, how about an option for telling it to use a pre-downloaded installer jar by giving a path into `/data`?

**Comment by Reviville** [comment]
you could implement that if you want, but tbh i don't think i would use that, as i like the fact that the image does take over that for me :D

**Comment by itzg** [comment]
In both cases (filename or URL) the Forge installer needs to be referenced since they populate the `libraries` directory during installation.

I have pushed this change, so it's ready for you to try out with [update docs here](https://github.com/itzg/dockerfiles/blob/master/minecraft-server/README.md#running-a-forge-server).

**Comment by Reviville** [comment]
Sorry for the delay, had a lot to do this weekend.
The FORGE_INSTALLER_URL works just fine and everything starts running.
But when i want to declare the FORGE_INSTALLER i get the following error:
![image](https://cloud.githubusercontent.com/assets/26972387/26779737/e339f4ca-49e6-11e7-91bc-9cae7b4cedbe.png)

**Comment by itzg** [comment]
@Reviville what's the `docker run` you're using when you get the error with `FORGE_INSTALLER`?

**Comment by Reviville** [comment]
The same im using when running the FORGE_INSTALLER_URL:

docker run -d -v /path/to/data:/data -e UID=1001 -e GID=1001 \
-e EULA=TRUE -e TYPE=FORGE -e FORGE_INSTALLER=/path/to/data/forge-1.8.8-11.15.0.1655-installer.jar \
-e INIT_MEMORY=1024M -e MAX_MEMORY=2048M -p 25565:25565 \
--name testuser-docker itzg/minecraft-server --noconsole

**Comment by itzg** [comment]
The path needs to be in the container's scope or more simply can be relative to `/data`, so this should work:

    -e FORGE_INSTALLER=forge-1.8.8-11.15.0.1655-installer.jar

**however** I need to investigate why it failed weirdly with an incorrect path :)

**Comment by itzg** [comment]
I pushed an update that'll now validate the given `FORGE_INSTALLER` file exists within the container.

**Comment by Reviville** [comment]
2 issues with this one:

before upgrading i saw that --noconsole is not supported. Even though it might not peg the CPU as much as Spigot/Bukkit it still feels better to implement it, as i do not need the console either for vanilla, nor for Forge (going with RCON)
![image](https://cloud.githubusercontent.com/assets/26972387/26823374/b29ddde6-4aad-11e7-9b53-085daf8e1323.png)


after upgrading i tried to execute the same docker run again, this time without --noconsole.
Unfortunately i got the following error (he does not install the Server automatically anymore, but he did before)
![image](https://cloud.githubusercontent.com/assets/26972387/26823427/e7217fb4-4aad-11e7-8341-0bc03c62bee2.png)

**Comment by itzg** [comment]
Thank you as always for the thorough feedback. 

I'm afraid the first one is beyond my control since it is the application jar itself processing the arguments there. It does seem very annoying to not be able to use a consistent command line, so I'm open to any ideas like simple version/type filtering away of that argument. 

I think I know what's going on with the second issue, so I'll be able to fix that.

**Comment by Reviville** [comment]
According to https://github.com/itzg/dockerfiles/issues/80 you implemented this OPTION, right? Probably you could rename or remove the '--' at least for forge, as forge expectes his '--installServer' right away.

**Comment by itzg** [comment]
Oh, I bet it's one in the same bug causing both issues. When using `FORGE_INSTALLER` the script uses a wildcard to try to find the server jar created by the forge installer. I'm pretty sure it's accidentally picking up the installer jar itself and trying to run it like a server. Maybe I should have it rename the installer jar after it's used then the "*.jar" type wildcard wouldn't pick it up.

**Comment by Reviville** [comment]
Most likely :p

**Comment by itzg** [comment]
OK, give the latest image a try. It now excludes a forge jar with "installer" in the name from the final server jar to run.

**Comment by Reviville** [comment]
I pulled the latest build, but nothing changed to be honest o.o

**Comment by itzg** [comment]
Weird. I'll push some "debug" output in there and have you check with that.

**Comment by itzg** [comment]
...pushed. First be sure to do a `docker pull itzg/minecraft-server`.

I'm testing using:

```
docker run -it --rm -e TYPE=FORGE -e FORGE_INSTALLER=forge-1.8.8-11.15.0.1655-installer.jar -e EULA=TRUE -v ${PWD}:/data itzg/minecraft-server
```

An expanded message is output before the forge installer runs:

```
Installing Forge  using forge-1.8.8-11.15.0.1655-installer.jar
```

and after installation there is a new "finding" message:

```
Finding installed server jar...
...forge-1.8.8-11.15.0.1655-installer.jar
...forge-1.8.8-11.15.0.1655-universal.jar
Using server forge-1.8.8-11.15.0.1655-universal.jar
```

Try that on your system and let's compare notes.

**Comment by Reviville** [comment]
I still had hidden files left, so it cached some shit....
Now everything works as expected <3

**Comment by itzg** [comment]
Excellent. Thanks.
