### ISSUE TITLE
Feed The Beast Support

### ISSUE THREAD

**Issue by Reviville** [itzg/dockerfiles#155]
Hey ho :)

I would like to ask you if you could try to implement support for "Feed The Beast", or in other words all the modpacks that come with it (https://www.feed-the-beast.com/modpacks)

Basically there is nothing different compared to Spigot/Bukkit to be honest.
An how to can be found here: https://www.feed-the-beast.com/hosting

The modpack would be easy to choose via FTB_DOWNLOAD_URL, so a general configuration would be cool :)
Its just unzipping the .zip file before running the server...

Could you take a look at that? :)

Thank you in advance, Lukas

**Comment by itzg** [comment]
You're in luck, it's already supported ;)

https://github.com/itzg/dockerfiles/tree/master/minecraft-server#running-a-server-with-a-feed-the-beast-ftb-modpack

I very recently added the support for `FTB_SERVER_MOD` to be a URL...however, it'll currently auto-append "/download" since I assume it's located in https://www.feed-the-beast.com/ . I can enhance that if you're wanting to host modpacks in your own repo.

**Comment by Reviville** [comment]
Oh wow sorry for that then... im blind

if i have to download the mod myself, everything is clear and no download_url is needed for me.
But thanks :)
You can close it if you want, you can obviously aso add a download_url option, as you wish :)

**Comment by itzg** [comment]
It's pretty easy to enhance that URL logic, so not assume it's "one of theirs" like https://www.feed-the-beast.com/projects/ftb-infinity-lite-1-10/files/2402889.

**Comment by Reviville** [comment]
Well, i will just download all modpacks i need and put them on my storage... from there i would download them and then move them to the data directory... thats fine for me :D

**Comment by itzg** [comment]
Cool. I think I'll enhance it anyway...that gap was bugging me before :)

**Comment by Reviville** [comment]
alright, ahve fun doing so :)
Thank you!

**Comment by jaymeprocera** [comment]
I'm getting an error trying to execute ServerStart.sh when trying to run FTB.  I have defined in a docker-compose like this:
    TYPE: "FTB"
    VERSION: "1.7.10"
    FTB_SERVER_MOD: "FTBInfinity-2.6.0-1.7.10.zip"

chmod: /data/FeedTheBeast/ServerStart.sh: No such file or directory
sed: /data/FeedTheBeast/ServerStart.sh: No such file or directory
Setting initial memory to 1G and max to 4G
cp: can't stat '/data/ops.txt': No such file or directory
cp: can't stat '/data/white-list.txt': No such file or directory
Running FTB server modpack start ...
sh: can't open '/data/FeedTheBeast/ServerStart.sh'

I can provide the full logs and docker compose if needed. Thanks for any help!

**Comment by itzg** [comment]
@jaymeprocera it looks like you might be running into a mistake I usually make, using the client zip instead of the server zip. Double check using the [FTBInfinityServer](https://www.feed-the-beast.com/projects/ftb-infinity-evolved/files/2320899) companion of that file.

**Comment by itzg** [comment]
@Reviville sorry, I managed to let this issue go stale. I finally added the tweak I mentioned and it's pushed to hub

https://hub.docker.com/r/itzg/minecraft-server/builds/bodo74mnshrycgnpsuktmry/
