### ISSUE TITLE
[Minecraft] Feature Requests: Graceful shutdown and Healthchecks

### ISSUE THREAD

**Issue by dschaper** [itzg/dockerfiles#159]
Based on some comments from another issue, there was a mention of a Java implementation to access the internal server running in container. This may be a good approach to implementing healthchecks on the running container, as I'm seeing the server go silent after some time running. 

This leads to the more pressing issue of needing some graceful shutdown in the entrypoint script. If there is a need to down the server, for now I'm needing to `exec` into `rcon-cli` and stopping the server there. With the default `restart always` this just starts the server right back up. Having code that traps the docker exit signaling and gracefully shutting down the server would be very helpful. 

I'll try to see what I can come up with in PR's to get things started, but my other projects are requiring lots of time, so I don't actually play my servers, just watch them for other players running on my nodes.

**Comment by itzg** [comment]
Good points. A companion tool inside the container could be used to performed [first class HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) operations. And yes, instead of propagating the SIGTERM, which ungracefully stops the minecraft server, that signal could be intercepted and invoke `rcon-cli stop`.

PRs, even partial, would be great. I can fill in remaining bits, etc.

**Comment by itzg** [comment]
Since it was fresh on my mind, I developed this little REST server:

https://github.com/itzg/mc-status

**Comment by itzg** [comment]
And now a one-shot, HEALTHCHECK friendly mode

https://github.com/itzg/mc-status#usage-as-a-one-shot-status-checker

**Comment by dschaper** [comment]
PayPal link? ;)

**Comment by itzg** [comment]
I do this all for fun, so I haven't yet posted this to the README :)

paypal.me/itzg

**Comment by dschaper** [comment]
Grab a beverage of your choice on me, thanks for everything!

**Comment by itzg** [comment]
Awesome, thanks, and you're very welcome

**Comment by itzg** [comment]
Thanks to @Reviville I was nudged into the direction of dinnerbone's mcstatus. The latest push now integrates that script and uses it for healthchecks.

Here's the new docs:
https://github.com/itzg/dockerfiles/tree/master/minecraft-server#healthcheck

**Comment by itzg** [comment]
### TODO

- [ ] Intercept ctrl-c/SIGTERM and invoke `rcon-cli stop`

**Comment by magneticflux-** [comment]
It looks like this is how you would intercept a SIGTERM: https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example

> Lastly, if you need to do some extra cleanup (or communicate with other containers) on shutdown, or are co-ordinating more than one executable, you may need to ensure that the ENTRYPOINT script receives the Unix signals, passes them on, and then does some more work:

**Comment by magneticflux-** [comment]
@itzg This Docker container has their intercept working correctly: https://github.com/mide/minecraft/blob/master/scripts/wrapper.py#L10. Perhaps you could reach out to them and get a Docker file that has the best of both worlds: Forge support, env variable configuration, and graceful shutdown + health checks.

**Comment by itzg** [comment]
Good idea and I can already see that I can combine a shell `trap` operation with the rcon-cli I wrote/bundle with the image.

**Comment by itzg** [comment]
I'm one step closer now with this little container entry wrapper working in local testing:

https://github.com/itzg/mc-server-runner

**Comment by itzg** [comment]
I have finally conquered this issue (in less than a year :( ). The latest image pushed to Hub now gracefully shuts down the minecraft server when handling a `docker stop`:

```
[20:30:35] [Server thread/INFO]: Done (14.783s)! For help, type "help" or "?"
[20:30:35] [Server thread/INFO]: Starting remote control listener
[20:30:35] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:25575
[20:30:38] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2133ms behind, skipping 42 tick(s)
2018/05/18 20:30:44 Sending 'stop' to Minecraft server...
2018/05/18 20:30:44 Waiting for completion...
[20:30:44] [Server thread/INFO]: Stopping the server
[20:30:44] [Server thread/INFO]: Stopping server
[20:30:44] [Server thread/INFO]: Saving players
[20:30:44] [Server thread/INFO]: Saving worlds
[20:30:44] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[20:30:45] [Server thread/INFO]: Saving chunks for level 'world'/the_nether
[20:30:45] [Server thread/INFO]: Saving chunks for level 'world'/the_end
[20:30:46] [Server Shutdown Thread/INFO]: Stopping server
[20:30:46] [Server Shutdown Thread/INFO]: Saving players
[20:30:46] [Server Shutdown Thread/INFO]: Saving worlds
[20:30:46] [Server Shutdown Thread/INFO]: Saving chunks for level 'world'/overworld
[20:30:46] [Server Shutdown Thread/INFO]: Saving chunks for level 'world'/the_nether
[20:30:46] [Server Shutdown Thread/INFO]: Saving chunks for level 'world'/the_end
2018/05/18 20:30:46 Done
```
