### ISSUE TITLE
Spigot Minecraft 1.12 Support

### ISSUE THREAD

**Issue by aamche** [itzg/dockerfiles#160]
Not sure if just me or waiting on a container update for 1.12 Spigot (appreciated the fact you maybe be busy).

Can't start a Spigot 1.12 instance. Build have been released on spigotmc.org. I'll pulled the latest version, help much appreciated.

Docker console logs  show,

`Switching to user 'minecraft'`
`Checking version information.`
`Checking type information.`
`2017/06/11 01:32:56 Unable to find an element with the class 'jar-div'`
`ERROR: Version 1.12 is not supported for SPIGOT`
`       Refer to https://mcadmin.net/ for supported versions`

**Comment by itzg** [comment]
Hmm, I'll take a look..

**Comment by itzg** [comment]
Well, I'll have to check later since their site is overloaded right now

![image](https://user-images.githubusercontent.com/988985/27012165-73249d58-4e90-11e7-99bb-203b8f8b6198.png)

**Comment by aamche** [comment]
Hmm, still borken. I've taken a guess at the admin email and emailed them. Could be broken for a while. What does mcadmin do?

**Comment by aamche** [comment]
Hmm, digging further using wayback machine I'm guessing that mcadmin is a repo for downloading compiled jars of spigot and craftbukkit.

Would it be possible to replace that with a spigot build process. I had a look around and there's a bit of code out there. This repo has a build process for spigot, that maybe a better fit
https://github.com/dlord/spigot-docker/blob/master/spigot

I'm getting to know docker and git better, but I'm not quite at the contribute stage yet, maybe in the near future.

**Comment by itzg** [comment]
You're in luck. Buried [way down in the README](https://github.com/itzg/dockerfiles/tree/master/minecraft-server#running-a-bukkitspigot-server) is an option to build from source within the container: `-e BUILD_FROM_SOURCE=true`

**Comment by aamche** [comment]
Ran into a git problem with that, possibly git missing from the container image.

I've move to specify my own url version to download and that seems to work
`SPIGOT_DOWNLOAD_URL`

Thanks for the help, and it's great you have all these different ways of getting it to work, great thinking.
