### ISSUE TITLE
Elasticsearch plugin is red

### ISSUE THREAD

**Issue by manojsb** [itzg/dockerfiles#168]
HI @itzg 

Just installed the cluster but getting following error in kibana:
```
This version of Kibana requires Elasticsearch v5.5.0 on all nodes. I found the following incompatible nodes in your cluster: v5.4.3.
```
Any solution ?

Thanks

**Comment by itzg** [comment]
I had to started on bumping the image to 5.5.0 and then got distracted with network issues. I'll wrap that up and that'll fix it.

**Comment by manojsb** [comment]
@itzg  I opened a pull request, can you check please If it's okay ?

**Comment by itzg** [comment]
ES 5.5.0 image is now pushed. Can you double check that resolves it for you?

**Comment by manojsb** [comment]
@itzg  Thank you so much. I will confirm you tomorrow once I get back to system.  Sorry for delay

**Comment by manojsb** [comment]
@itzg  Hi I have testing it. its working perfectly. I synced mongodb data through logstash to this ES cluster.

Thanks you so much
