### ISSUE TITLE
Container starts and then goes right to exit

### ISSUE THREAD

**Issue by adamras** [itzg/dockerfiles#178]
Hey man. Thanks for putting this together. I am having the container start and then immediately go into exit status. This is regardless of how many parameters I am trying to pass. Do you, or anyone else from the community have any insight as to why this might be? Thanks in advance!

**Comment by itzg** [comment]
You're welcome.

Hmm, I just double checked by doing a fresh docker pull and it started fine for me. Does it give any output at all before exiting?

**Comment by adamras** [comment]
Brother, all I needed to do was sleep on it I guess.  I don't know what I was missing before but it seems to have remedied itself.  Thanks for replying...so quickly too.

**Comment by itzg** [comment]
Awesome
