### ISSUE TITLE
mcadmin.net is down

### ISSUE THREAD

**Issue by SireneKatze5872** [itzg/dockerfiles#181]
Hey itzg

Somehoy the mcadmin.net domain is down and the docker container can't download any Spigot, Craftbukkit version anymore. Can you please fix that ?

**Comment by SireneKatze5872** [comment]
https://getbukkit.org/download/
would be an alternative

**Comment by itzg** [comment]
Thank you for pointing out the alternate site. Hopefully that one is more reliable than mcadmin. For now you can point to their downloads using '-e BUKKIT_DOWNLOAD_URL'

**Comment by itzg** [comment]
Interesting...as of the 1.11 versions the getbukkit URLs become derivable such as

https://cdn.getbukkit.org/spigot/spigot-1.11.jar

**Comment by raix** [comment]
https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.12.2.jar

**Comment by OnlyBrakeForRainbows** [comment]
Just about to post an issue about this, also [Yives Mirror](https://yivesmirror.com/) hosts a plethora of images

**Comment by itzg** [comment]
I like the breadth of Yives, but I'm not seeing a REST API that could be leveraged. In any case, between Yives and getbukkit this does seem to be solvable.

**Comment by OnlyBrakeForRainbows** [comment]
I know of a very lively discord channel for yives that may be of help re: the api

**Comment by itzg** [comment]
That would be great @OnlyBrakeForRainbows . It does feel like Yives is super close to what would be needed.

**Comment by OnlyBrakeForRainbows** [comment]
Yeah it is a good source apparently the address is https://discord.gg/KFEXyhH

**Comment by itzg** [comment]
Sorry for the wait everyone, but I have pushed an update to Hub that downloads Bukkit and Spigot reliably from getbukkit.org. Try it out and comment here if the new solution doesn't work.
