### ISSUE TITLE
Level type request

### ISSUE THREAD

**Issue by tiilikainen** [itzg/dockerfiles#182]
Hi,

Please add LEVEL_TYPE of RTG to the list of valid level types. This one is used by the Realistic Terrain Generation mod.

**Comment by itzg** [comment]
This fix is now pushed to Hub.

FYI, I tested using 

```
mkdir rtg
mv RTG-1.10.2-4.1.2.4.jar rtg
docker run -it --rm -e EULA=TRUE -e TYPE=FORGE -e VERSION=1.10.2 -v ${PWD}/rtg:/mods -e LEVEL_TYPE=RTG -p 25565:25565 itzg/minecraft-server
```
