### ISSUE TITLE
[minecraft-server] Client fails to connect to 1.13 snapshot

### ISSUE THREAD

**Issue by jbruni** [itzg/dockerfiles#199]
The docker server runs, but when we try to connect, client breaks (both Mac client and Windows client).

I've used "latest" **18w07b** snapshot (not "latest" anymore since a couple of hours ago), like this:

```
docker run -d -e VERSION=SNAPSHOT -e EULA=TRUE -v /home/jbruni/mc-world:/data -p 25565:25565 --name mc itzg/minecraft-server
```

After stopping the container and cleaning up (`rm -rf /home/jbruni/mc-world`, etc), I've then used the exact same command and setup, in same server, only changing the `VERSION` to `1.8`, and it worked flawlessly. We were able to connect and play using 4 distinct clients.

I'm not sure if this is an issue with the snapshot server jar itself or with the docker wrapper.

**Comment by itzg** [comment]
Thanks for reporting this. Yes, I have just noticed the same thing so I’ll investigate more if it’s the image or the snapshot jar itself.

**Comment by itzg** [comment]
OK, I have confirmed that the client also crashes when connecting to a direct `java -jar` execution of https://launcher.mojang.com/mc/game/18w07c/server/52e141870c3c850811710f2ba07eb3e7e583ea92/server.jar

The client logs show an NPE:

```
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at vn$a.a(SourceFile:77)
	at vn$a.a(SourceFile:63)
	at axq.a(SourceFile:210)
	at bfs.a(SourceFile:263)
	at abd.a(SourceFile:1105)
	at ckd.b(SourceFile:1183)
	at ckd.a(SourceFile:1083)
	at ckd.a(SourceFile:944)
	at bxe.b(SourceFile:820)
	at bxe.a(SourceFile:381)
	at net.minecraft.client.main.Main.main(SourceFile:141)
```

**Comment by jbruni** [comment]
Indeed... I have just tried current latest snapshot **18w08b** using the same docker command from opening post... the error log now is slightly different, but I've found two things:

- this is a known issue
- there is a workaround

The workaround is:
1. Start Minecraft and start playing a Singleplayer game.
2. Disconnect to return to main menu
3. Join Multiplayer game

It works! We are able to join the server and play.

Reference: https://bugs.mojang.com/browse/MC-125451

**Comment by itzg** [comment]
@jbruni thanks for following up and the specific issue link. I noticed the past two release notes mentioned attempted fixes :)

**Comment by itzg** [comment]
I have noticed any issues with this lately, so I'll close this but can re-open if anyone bumps into this again.

**Comment by jbruni** [comment]
That's fine. The issue was with the Minecraft server itself, not with the docker wrapper. Thanks a lot for your super nice work on it!
