### ISSUE TITLE
docker engine marks container as unhealthy with other ports than default

### ISSUE THREAD

**Issue by TheLeftMoose** [itzg/dockerfiles#200]
Running with custom port, it seems like docker sees the health check as unhealthy for some reason. 

Any ideas what this could be caused?

**Comment by TheLeftMoose** [comment]
from docker ps

dsk@ubuntuserver:/data/newminecraft/survival10$ docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                      PORTS                                                                        NAMES
1852b29f8c3e        itzg/minecraft-server       "/start"                 13 minutes ago      Up 13 minutes (unhealthy)   25565/tcp, 25575/tcp, 0.0.0.0:25571->25571/tcp                               survival10

**Comment by TheLeftMoose** [comment]
so, using mcstatus is a good thing, though you need to specify what server exactly you want to monitor.

As I introduced the possibility to ser the port per env, this also lead to docker to mark the specific container as unhealthy as mcstatus now fails. In the Dockerfile we have specified specifically that it should only look at:
`HEALTHCHECK CMD mcstatus localhost ping`

This is a great thing for convience if you only run one server, though for multible servers on the same host... you usually set a specific port the server should run on.

It seems like you can overwrite this in your run command or docker-compose file:

Run command:
docker run --name=foo -d \
    --health-cmd='mcstatus localhost:25571 ping' \
    --health-interval=2s \

or 

docker-compose:
`   healthcheck:
      test: ["CMD", "mcstatus", "localhost:25571", "ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3`


Maybe somebody should document this...

**Comment by itzg** [comment]
@TheLeftMoose I'm going to close this issue since the HEALTHCHECK is baked into the image, but then overrideable as you noted. IMHO, it's rare that the server port within the container should need to be altered since that's the beauty of containers and isolated networking namespaces.

Let me know though if you think there's a way the base image could support the variable health check arguments.
