### ISSUE TITLE
Unable to allocate more RAM for Forge/ Age of Engineering

### ISSUE THREAD

**Issue by EvgenyPoletaev** [itzg/dockerfiles#201]
used command : 
docker run -it -d -e MIN_RAM=2G -e MAX_RAM=2G -v /home/mcserver/host:/data -e TYPE=FORGE -e FORGE_INSTALLER=install.jar -p 25565:25565 -e EULA=TRUE --name servermc itzg/minecraft-server

And it installs, and runs server fine, however it doesnt allocate more than 1 GB of RAM -
Setting initial memory to 1G and max to 1G
Tried Xms2G with no success.

**Comment by itzg** [comment]
I had to look in the docs since I had forgotten, but the variables are actually `MAX_MEMORY`, `INIT_MEMORY`, or `MEMORY` to set both. Such as:

```
docker run -it -d -e INIT_MEMORY=1G -e MAX_MEMORY=2G -p 25565:25565 -e EULA=TRUE --name servermc itzg/minecraft-server
```

**Comment by EvgenyPoletaev** [comment]
Thanks
