### ISSUE TITLE
Minecraft - FTB -> ServerStart.sh not found

### ISSUE THREAD

**Issue by Wiamor** [itzg/dockerfiles#203]
I pulled your repo and changed the docker-compose file like discribed, so that i would then run a FTB-server, but no matter what modpack itry to referance in the .yml, i get the same error, after the mod got downloaded.

`minecraft_1  | cp: can't stat '/data/ops.txt': No such file or directory
minecraft_1  | cp: can't stat '/data/FeedTheBeast/white-list.txt': No such file or directory
minecraft_1  | Running FTB server modpack start ...
minecraft_1  | /start-minecraftFinalSetup: line 94: /data/FeedTheBeast/ServerStart.sh: No such file or directory
minecraftserver_minecraft_1 exited with code 127
`
here what my .yml looks like

> version: '3'
>
>services:
>  minecraft:
>    image: itzg/minecraft-server
>    ports:
>      - "25565:25565"
>    volumes:
>      - "mc:/data"
>    environment:
      EULA: "TRUE"
      TYPE: "FTB"
      FTB_SERVER_MOD: "https://www.feed-the-beast.com/projects/ftb-revelation/files/2529434/download"
      CONSOLE: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "*******"
      RCON_PORT: 28016
    restart: always
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"
>
>volumes:
  mc:
  rcon:

if i check the volume, it has the FeedTheBeast folder in it

**Comment by itzg** [comment]
Thanks for reporting the issue. I have pushed the fix to Hub.
