### ISSUE TITLE
Java Crashing 5 minutes into game play

### ISSUE THREAD

**Issue by OnlyBrakeForRainbows** [itzg/dockerfiles#205]
The latest version on alpine is `8u151` and the Dockerfile is using `8u131` I don't know if this would help?

I'm using spigot 1.12.1 for reference, memory is setup correctly also

**Comment by OnlyBrakeForRainbows** [comment]
Jeez, what an oversight on my behalf, out of disc space (in my virtual machine) no wonder it's crashing...

**Comment by itzg** [comment]
I certainly could/should bump the base image to the latest Java 8 version, but like you, I'm not sure if that would help what you're experiencing.

**Comment by itzg** [comment]
...well, I'll have to try again later according to the apk update error:

```
Step 1/17 : FROM openjdk:8u151-jre-alpine
 ---> b1bd879ca9b3
Step 2/17 : LABEL maintainer "itzg"
 ---> Using cache
 ---> 90c62e82335b
Step 3/17 : RUN apk add -U           openssl           imagemagick           lsof           su-exec           bash           curl iputils wget           git           jq           mysql-client           python python-dev py2-pip &&         rm -rf /var/cache/apk/*
 ---> Running in 8e2a77117b82
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: BAD signature
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
```

**Comment by OnlyBrakeForRainbows** [comment]
Cool no problem it's weird how it's only on the alpine Linux version however the debian derivatives are running well

**Comment by itzg** [comment]
I pushed an update to hub that is now based on 8u151...I'm hoping that fixes it for you.

**Comment by OnlyBrakeForRainbows** [comment]
Cool thanks will spin a fresh up over the weekend and see if that improves anything

**Comment by OnlyBrakeForRainbows** [comment]
More stable but missing / not producing chunks, very strange, I'll give this a close however, thank you for your time.
