### ISSUE TITLE
Minecraft Docker - Failed to connect to world

### ISSUE THREAD

**Issue by FrizzMT** [itzg/dockerfiles#207]
Hello, sorry but I am a total beginner to containers, dockers, VMs, virtual switches. I would like to get the minecraft server docker working for my kids.

I have a QNAP TS 453 Pro. Plenty RAM and disk space.
Set up my virtual switch.
Using QNAP Container Station I downloaded the Minecraft Docker/container
I set the container network mode to bridged and static IP 10.0.1.24 and to connect via the virtual switch which is attached to one of my 4 physical adapters that connect to my physical home switch.
I can run the container. I see in the console that "RCON Running on 0.0.0.0:22575"
Using my kids login, I open minecraft I add the new server at 10.0.1.24 and port 22575.
It reports "Failed to connect to world".
I can ping 10.0.1.24 so I know the container is reachable.
There is a EULA text file which already contains EULA=TRUE (I read that this needs to be set)

What might I have missed? Are there some commands I need to input?

**Comment by itzg** [comment]
I don’t have personal experience with QNAP appliances, but from what I found of their docs you’ll neeed to look on the container page to see what port mapping it assigned for 25565, which is the actual MC server port. The RCON port, which you’re seeing in the logs, is used for administration and won’t be immediately useful.

**Comment by FrizzMT** [comment]
Ok, I have discovered the source of the issue. I purchased the xbox console version of Minecraft for Windows 10. While the console version can share games on the LAN from within the game to other LAN and WAN players, it does not support private LAN servers. It only supports servers provided by Mojang partners.
