### ISSUE TITLE
Feature Request: Add environment variable to allow flying on the server.

### ISSUE THREAD

**Issue by jasemi** [itzg/dockerfiles#208]
I would find it useful to have the option to set allow-flight=true in the server.properties file with a -e parameter to the docker run command.
Editing the server.properties file in a container directly doesn't seem to have the desired effect (I still get kicked when using a jetpack etc.).
Correct me if I'm wrong but i believe it may be due to the containers environment variables overriding the setting.

**Comment by itzg** [comment]
This is now published to hub. The new option is `-e ALLOW_FLIGHT=TRUE|FALSE`
