### ISSUE TITLE
su: System error

### ISSUE THREAD

**Issue by dottorblaster** [itzg/dockerfiles#21]
Hi, 
I'm starting a container with your dockerfile,

I keep getting this:

```bash
azureuser@blastercraft:~$ sudo docker run -d -it --name mc -e EULA=TRUE -p 25565:25565 -v /opt/craft/:/data itzg/minecraft-server
2e021c0aac782c28e9a78189164f06aa85d91a97086f6ed193f493adcb2f033b
azureuser@blastercraft:~$ sudo docker logs mc
usermod: no changes
su: System error
azureuser@blastercraft:~$
```

What the heck? :-/ Why is it working for everyone but me? .-. (as I can see...)

**Comment by itzg** [comment]
Let's gather some data points

* What's is your host OS and version
* Kernel version specifically
* Docker version 
* Do you have a user on your host system already with uid 1000?

**Comment by dottorblaster** [comment]
Well:

- Ubuntu 14.04
- 3.16.0
- Docker 1.0.1, API 1.12, Go 1.2.1
- Yep, it's azureuser

I'm on an Ubuntu machine on Azure, if it can help.

I finally started the container, but it works in an unexpected way because I have to bypass the su instruction. I'm testing a sudo version of the image right now and it seems to behave better.

**Comment by itzg** [comment]
Strange,  but good. That Docker version is a little old, but not sure if it would influence this.

Feel free to submit a pull request, if your adjustment works for you. I'll also work on a `-e UID=0` option to bypass the su/sudo altogether when it doesn't cooperate.

**Comment by dottorblaster** [comment]
I can try on my Ubuntu 14.10 when I get home, and on a virtual Fedora I have on my Mac. Maybe with a more recent version of Docker I can figure out what's happening, right now I actually start the container but nothing happens, I have to do a docker attach and a /start-minecraft manually to get things done. It's a big step forward in deploying a server by myself (without having to do with properties and so on) but I want much automation :D

I'll try to dive into this, I'm new to docker but I like it very much so this issue is so challenging.

**Comment by itzg** [comment]
My machine where I run my Minecraft images is also 14.04, so that's probably not it either.

Yeah, I was going to say a workaround is to start the image with `/start-minecraft`, such as

    docker run ... itzg/minecraft-server /start-minecraft

Yes, Docker does present some fun challenges to conquer.

**Comment by dottorblaster** [comment]
I'm getting completely fine with

```
/start-minecraft
```

at the end of file. The problem is, if I switch user I get a 

```
Error: -jar requires jar file specification
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
```

for the jar execution. Wadda hell... maybe switching the user it loses all the env vars? I don't understand. I would like to introduce sudo for this purpose, because on Ubuntu su is deprecated.

**Comment by itzg** [comment]
@dottorblaster, swapping out `su` for 

    exec sudo -u minecraft /start-minecraft

working for you? Or does it need to kick off a bash? (I'm being lazy and not just experimenting :) )

**Comment by itzg** [comment]
...ah, needs to preserve the environment: `sudo -E`

**Comment by itzg** [comment]
@dottorblaster , the sudo usage is in the latest pushed image, 8651fba4d9cf. Can you test it out?

**Comment by dottorblaster** [comment]
I don't have the laptop right now, i'll test it out asap :-)
Il 28/mar/2015 19:37 "Geoff Bourne" <notifications@github.com> ha scritto:

**Comment by dottorblaster** [comment]
It works like a charm! Thank you, I didn't know about sudo -E, thanks a lot :-)

**Comment by itzg** [comment]
Excellent
