### ISSUE TITLE
Can someone explain me these lines?

### ISSUE THREAD

**Issue by RoboFlax** [itzg/dockerfiles#210]
https://github.com/itzg/dockerfiles/blob/2627317e03617fbe4de424e2effcd63df9798a46/minecraft-server/start#L4
https://github.com/itzg/dockerfiles/blob/2627317e03617fbe4de424e2effcd63df9798a46/minecraft-server/start#L5

**Comment by RoboFlax** [comment]
linked with https://stackoverflow.com/questions/49833264/can-someone-explain-me-these-sed-commands-and-what-they-are-doing

**Comment by itzg** [comment]
And your SO question got a great answer

https://stackoverflow.com/a/49833320/121324
