### ISSUE TITLE
Server not following UID, GID in docker-compose definition

### ISSUE THREAD

**Issue by chris42** [itzg/dockerfiles#213]
Hi there,

after updating the image for the fix for Issue #211  (Seems to be working) , I could not start the server. It would tell me, that /data is no writable for my selected user. However when checking file permissions, they were correct.

Removing the folder and let the server start with empty data did not work either, as the folders are created as root and not as the selected user. Correction of permissions got me to the error above.

Workaround: Removing UID, GID from the docker-compose and let the server start on empty data creates everything with 1000:1000 and the server starts correctly. 
Hence using my old data with this permissions and no UID, GID definition in docker-compose worked as well.

Despite the workaround something seems to be wrong.

Regards
  Chris

**Comment by chris42** [comment]
The `user` statement works when giving the UID. To use the Username, it apparently has to exist in host and container. Hence UID is easier.
Documentation probably should be updated.

**Comment by chazily** [comment]
Trying to get this to work on a Synology NAS. Admittedly I am a bit of a novice on Linux, so please bear with me. Is this doable by adding an environment variable within the Docker container? Do I have to SSH into my NAS to modify a file? Thanks for any help.

**Comment by chris42** [comment]
The user statement can be passed via command line or the docker compose to the container. I am not sure how Synology handles this.
However I am not sure if this is needed. I would guess, that Synology sets the right user to interact with the NAS file system or uses volumes. 
In my case it is more a personal note, that all docker data is stored under a nologin user in the filesystem. Are you getting an error?

**Comment by 2vcps** [comment]
I am having this issue when running in Kubernetes. So I am clear, does the user 'minecraft' have to exist on the host?

**Comment by itzg** [comment]
@2vcps can you share some of the permission errors you see? I was expecting the `securityContext` setting to be optional since the image itself defaults to `USER minecraft`, which has a UID of 1000. In your case was the persistent volume pre-existing with file ownership of uid 1001?

**Comment by itzg** [comment]
BTW, the motivation for the change was to be able to avoid running the container as root via restrictions such as

```
  securityContext:
    runAsNonRoot: true
```

**Comment by 2vcps** [comment]
@itzg I was able to get it to work with UID 1000 (thinking this was less important). What really seems to be happening if I don't include the fsGroup: 2000 the mounted directory is owned by root:root and the user minecraft can't write to it. So I get permission denied when /start tries to create the eula.txt file.

**Comment by itzg** [comment]
Thanks, that’s an excellent data point. As a side note I had noticed Swarm attaching the volume owned as root but it had honored the 0777 permissions set in the image.

**Comment by 2vcps** [comment]
I tested this with rook and the purestorage flex volume drivers. So I don't "think" it is the underlying storage systems just something about the way k8s behaves.

**Comment by anthonyhou04** [comment]
I am a synology NAS user. I experienced this problem as well, any solution to that?

**Comment by itzg** [comment]
Since I don’t have access to test a Synology NAS, I can only go off of their online docs. As such, making sure to leave off the “Execute container using high privilege” option? Is there a way to specify the file system ownership of the Synology volumes? It needs to be owned by UID 1000 since they don’t seem to have a way of specific the container user like the “-u” option.

**Comment by anthonyhou04** [comment]
thanks, I will try that.

**Comment by Roemer** [comment]
Could someone run the server now on a Synology NAS with the data volume?

**Comment by Roemer** [comment]
What fixed it for me was to just give the docker volume (on the NAS) read/write permissions to everyone. Not the very best approach but it works.

**Comment by itzg** [comment]
@anthonyhou04 from that output it looks like Synology is running the container as uid=1026 yet the default uid in the image is 1000. I did a quick google for Synology NAS config, but couldn't see how to do the equivalent of `docker run --user 1026 ...`. Any ideas there?

**Comment by anthonyhou04** [comment]
Hi, thank you for replying. I used ssh to manually create a Docker container instead of using Synology Docker Tool. With "--user 1026" added to the command, I was able to create a running server successfully.
Thank you again!

**Comment by itzg** [comment]
Fixed in 848cd8b994bba2902e2a2f48bf616b9bfa107800 and pushed to Docker Hub.
