### ISSUE TITLE
Acceptin EULA problems when restarting container

### ISSUE THREAD

**Issue by gaborfinta** [itzg/dockerfiles#219]
Hi,
After stopping a freshly created container and using the docker start mc command, the container doesn't start and the docker logs mc says that I'm supposed to accept the eula with the run command. The weird thing it that when the container was created with run, it got the -e EULA=TRUE option and the container is up and running after that. The problem occurs only after stopping and starting again.
Any idea what can cause this problem or what I'm missing here?

**Comment by itzg** [comment]
I’ll have to investigate since I would have expected the `docker start` to retain the environment variables.

**Comment by itzg** [comment]
@gaborfinta , I wasn't able to re-create this. Can you double check that the container you're `start`ing has the environment set as you expect using something like `docker inspect mc -f "{{.Config.Env}}"`?

**Comment by gaborfinta** [comment]
I honestly don't know what caused the problem. Nothing helped last time but not it works. Maybe it's just the pc restart since then. Thanks for your quick replies though

**Comment by itzg** [comment]
I'm glad to hear it mysteriously resolved itself.
