### ISSUE TITLE
[request] any suggestions for a way to have it run on pi3 

### ISSUE THREAD

**Issue by marxenegls** [itzg/dockerfiles#221]
how should i go about building a dockerfile for a raspbian based image 
i have a cluster of four but not sure if swarm mode gets the memory shared as a whole group or individual nodes each node has 970Mb of ram .
i doubt just editing the ENV param to arm32v7 will do, i'm guessing the restify , rcon-cli and mc-server need to be recompiled ?

thanks

**Comment by marxenegls** [comment]
i found it you already have a raspberyypi image 
thanks

**Comment by itzg** [comment]
@marxenegls yeah, it's most of the way there, but Docker Hub doesn't natively allow building non-x86 images. Let me see if this approach from resin.io will get it the rest of the way.

But yes, in the meantime you could git clone the repo, which has a lot of directories but is pretty small in overall size, and build in the minecraft-server directory:

```
git clone https://github.com/itzg/dockerfiles.git
git checkout mc/raspberrypi
cd minecraft-server
docker build -t mc .
```

**Comment by itzg** [comment]
This is related to #114

**Comment by itzg** [comment]
The image built successfully as the tag `raspberrypi`. I am currently testing using:

```
docker pull itzg/minecraft-server:raspberrypi
```

**Comment by marxenegls** [comment]
thanks appreciate your quick reply ... 
i promised my kid i'd set it up she loves minecraft but is very very particular as to what can and can not be in her world , no zombies, no hunts, no battles, no sudden movements ..etc plus she'd like to be able to invite her girlfriends , so i figured her own server would be safest bet.

**Comment by itzg** [comment]
You'll definitely want to increase the `-e MEMORY=...` setting from the "50M" in the default. I based that off of my Model B Rev 1.0, but am finding I can increase a bit more now that I have a fully working image.

**Comment by marxenegls** [comment]
docker run -d -it -v `pwd`:/data -e EULA=TRUE -e MEMORY="300M" -p 25565:25565 --name mc1 itzg/minecraft-server:raspberrypi 
i got running but i'm having difficulties reaching it .. on -p 25565 ,
ran a netstat and saw :::25565. i tried setting host ip manually in server.properties but it refused to start, i the set the ip to 0.0.0.0 instead and it's holding up, also set the monster spawning to false.
added a /plugins dir and scp EssentialsX-2.0.1.jar + Vault.jar apparently a depend of EssentialsX and pushed forge-1.12.2-14.23.4.2705-universal.jar to /mods dir

what am i doing wrong

**Comment by marxenegls** [comment]
i think i got something in the logs it seems jvm is set to 1024 
 it's also pulling down another minecraft.jar i have one in data volume - i guess it always does that 
logs:
Checking version information.
Checking type information.
Downloading minecraft_server.1.12.2.jar ...
Creating server.properties in /data/server.properties
Setting server-port to '25565' in /data/server.properties
Setting motd to 'A Vanilla Minecraft Server powered by Docker' in /data/server.properties
Skip setting allow-nether
Skip setting announce-player-achievements
Skip setting enable-command-block
Skip setting spawn-animals
Skip setting spawn-monsters
Skip setting spawn-npcs
Skip setting generate-structures
Skip setting view-distance
Skip setting hardcore
Skip setting snooper-enabled
Skip setting max-build-height
Skip setting force-gamemode
Skip setting hardmax-tick-timecore
Skip setting enable-query
Skip setting query.port
Setting enable-rcon to 'true' in /data/server.properties
Setting rcon.password to 'minecraft' in /data/server.properties
Setting rcon.port to '25575' in /data/server.properties
Skip setting max-players
Skip setting max-world-size
Setting level-name to 'world' in /data/server.properties
Skip setting level-seed
Setting pvp to 'true' in /data/server.properties
Skip setting generator-settings
Setting online-mode to 'true' in /data/server.properties
Skip setting allow-flight
Setting level type to DEFAULT
Setting level-type to 'DEFAULT' in /data/server.properties
Setting difficulty to '1' in /data/server.properties
Skipping JSON check. No files present.
Setting initial memory to 300M and max to 300M
Java HotSpot(TM) Client VM warning: G1 GC is disabled in this release.
[19:57:33] [Server thread/INFO]: Starting minecraft server version 1.12.2
[19:57:33] [Server thread/WARN]: To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
[19:57:33] [Server thread/INFO]: Loading properties
[19:57:33] [Server thread/INFO]: Default game type: SURVIVAL
[19:57:33] [Server thread/INFO]: Generating keypair
[19:57:36] [Server thread/INFO]: Starting Minecraft server on *:25565

Java HotSpot(TM) Client VM warning: You have loaded library /tmp/libnetty-transport-native-epoll29336838761112090.so which might have disabled stack guard. The VM will try to fix the stack guard now.

It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-znoexecstack'.
[19:57:37] [Server thread/INFO]: Using default channel type
[19:57:37] [Server thread/INFO]: Preparing level "world"
[19:57:40] [Server thread/INFO]: Loaded 488 advancements
[19:57:47] [Server thread/INFO]: Preparing start region for level 0
[19:57:48] [Server thread/INFO]: Preparing spawn area: 0%
[19:57:49] [Server thread/INFO]: Preparing spawn area: 2%
[20:01:43] [Server thread/INFO]: Preparing spawn area: 99%
[20:01:44] [Server thread/INFO]: Done (246.992s)! For help, type "help" or "?"
[20:01:44] [Server thread/INFO]: Starting remote control listener
[20:01:44] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:25575
[20:02:01] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 16038ms behind, skipping 320 tick(s)
[20:02:07] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6547ms behind, skipping 130 tick(s)
[20:03:03] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 14461ms behind, skipping 289 tick(s)
Checking version information.

Checking type information.
server.properties already created, skipping
Skipping JSON check. No files present.

Setting initial memory to 300M and max to 300M
Java HotSpot(TM) Client VM warning: G1 GC is disabled in this release.
[21:46:25] [Server thread/INFO]: Starting minecraft server version 1.12.2
[21:46:25] [Server thread/WARN]: To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"

**Comment by marxenegls** [comment]
see it, RCON returns actual time and server freaks out cant keep up what's happening .. 
tried using sudo to cp zoneinfo and even set passwd of coarse to use sudo edit etc etc
read a suggestion of using -v /etc/localtime . i'll stop the server add more ram and set time and let you know what gives

**Comment by marxenegls** [comment]
same thing 

[03:21:40] [Server thread/INFO]: Preparing spawn area: 83%
[03:21:41] [Server thread/INFO]: Preparing spawn area: 88%
[03:21:42] [Server thread/INFO]: Preparing spawn area: 94%
[03:21:43] [Server thread/INFO]: Done (34.769s)! For help, type "help" or "?"
[03:21:43] [Server thread/INFO]: Starting remote control listener
[03:21:43] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:25575
[03:22:30] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2419ms behind, skipping 48 tick(s)

the date/time now though matches that of the host, i checked  

 docker run -d -p 25565:25565 -v /etc/localtime:/etc/localtime:ro -v `pwd`:/data -e EULA=TRUE -e MEMORY="600M" --name mc1 itzg/minecraft-server:raspberrypi 

is it the fact that image is compiled for cpu armv6 - i'm on a pi3  armv7 related  ? clock speed ??
:(

**Comment by marxenegls** [comment]
i stumbled on blog with a similar project ...
(https://www.jamesachambers.com/2018/03/fast-raspberry-pi-minecraft-server-install-script/) 
i read up on jvm -XX opt and it seems GC opt is for multi threaded big ram capacity machines .
JVM_XX_OPTS ="XX: -Xss320K  -Xms 600M -Xmx800M" seems more adequate for arm devices
there's an available openjdk-9-jdk-headless 
and tweaked the hertz of sdCard read/write speed + armv7
i've edited the dockerfile but it not enough i'd hate to start pulling another image or a piece of one , at this point i]m doubting whether to install it or run inside a docker - 
i got two days left before school is out .

**Comment by itzg** [comment]
Honestly, I'm not impressed at all with the performance of the Minecraft server on RaspberryPi. The RaspberryPi is just too underpowered for the official server, which assumes large amounts of RAM (as you saw from its suggestion about using 1024m) and large amounts of floating-point compute capacity.

As evidence, the RaspberryPI foundation bundles a build of Minecraft, but I assume they have highly optimized (i.e. stripped down) that implementation.

Regarding your previous comments:
* Yes, one of the main benefits of the image is auto-downloading the requested version of minecraft server, so you do not need to provide the jar for it
* The mention of `launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"` is their server itself suggesting that 1024m be the **minimum** memory allocated
* I believe armv6 compilation should be forward compatible with armv7; however, at that point its Java code being executed by Oracle ARM build of the JVM
* The clock skew is evidence of my concern noted above: the hardware is underpowered for the official server jar
