### ISSUE TITLE
XMX settings not taken over.

### ISSUE THREAD

**Issue by TrueOsiris** [itzg/dockerfiles#222]
my docker command:

docker run -d --name='minecraft-3' --net='bridge' -e TZ="Europe/Paris" -e HOST_OS="unRAID" -e 'VERSION'='1.10.2' -e 'MAX_PLAYERS'='20' -e 'MIN_RAM'='4G' -e 'MAX_RAM'='8G' -e 'PERMGEN_SIZE'='512M' -e 'DIFFICULTY'='easy' -e 'ENABLE_RCON'='true' -e 'ENABLE_QUERY'='true' -e 'QUERY_PORT'='25567' -e 'ANNOUNCE_PLAYER_ACHIEVEMENTS'='true' -e 'ALLOW_NETHER'='true' -e 'FORCE_GAMEMODE'='true' -e 'MAX_TICK_TIME'='60000' -e 'SPAWN_ANIMALS'='true' -e 'SPAWN_MONSTERS'='true' -e 'SPAWN_NPCS'='true' -e 'VIEW_DISTANCE'='20' -e 'MODE'='survival' -e 'MOTD'='FTB SkyFactory3' -e 'PVP'='false' -e 'LEVEL'='wereld3' -e 'EULA'='TRUE' -e 'RCON_PASSWORD'='jibberish' -e 'OPS'='jibberishtoo' -e 'RCON_PORT'='25577' -e 'ICON'='http://www.rw-designer.com/icon-image/5547-256x256x32.png' -e 'TYPE'='FTB' -e 'FTB_SERVER_MOD'='FTBPresentsSkyfactory3Server_3.0.15.zip' -e 'INIT_MEMORY'='4G' -e 'MAX_MEMORY'='8G' -p '25567:25565/tcp' -p '25567:25565/udp' -v '/mnt/user/docker/minecraft-3':'/data':'rw' 'itzg/minecraft-server'

results in

ps -auxw | grep FTB

java -server -Xms512M -Xmx3072M -XX:PermSize=256M -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -Dfml.queryResult=confirm -Dfml.queryResult=confirm -Dfml.queryResult=confirm -Dfml.queryResult=confirm -jar FTBserver-1.10.2-12.18.3.2477.jar nogui

Am I doing something wrong?

**Comment by itzg** [comment]
Your attempt was correct, but it looks the startup script isn't propagating those to the invocation of FTB at

https://github.com/itzg/dockerfiles/blob/master/minecraft-server/start-minecraftFinalSetup#L94

Since FTB provides a wrapper script I'll have to investigate what it will take to override their final invocation of java.

**Comment by TrueOsiris** [comment]
actually, when I try it without the FTB, it gives me the same result.

**Comment by TrueOsiris** [comment]
Indeed, when I try this with a normal minecraft (v1.12.2) server, the 8G propagates to an XMX of 8G

**Comment by BakermanLP** [comment]
As far as I tested it, the following should work:
"-e MEMORY=4G"

**Comment by TrueOsiris** [comment]
It does not. I have played with all the memory parameters now, to no avail. It keeps starting with the exact same xms / xmx settings, even if I omit all parameters.

**Comment by itzg** [comment]
Unfortunately that's what I would have expected. OK, I'll dig into the server wrapper script that comes with a typical FTB bundle and see if there's a standard way to pass JVM options to it.

**Comment by itzg** [comment]
This is now published to Hub.
