### ISSUE TITLE
Minecraft docker ignores -e MAX_RAM

### ISSUE THREAD

**Issue by tjsd** [itzg/dockerfiles#229]
So I have a docker running now with the following launch parmeters

docker run -d -it -v /home/minecraft/mc-docker:/data \
-e VERSION=1.12.2 -e TYPE=FORGE -e FORGEVERSION=14.23.4.2739 \
-e MAX_RAM=8G \
-e JVM_XX_OPTS='-Xmx8G -d64 -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:CompileThreshold=1500 -Xnoclassgc -Xverify:none -XX:UseSSE=3 -XX:+UseThreadPriorities -Djava.net.preferIPv4Stack=true -Dfml.readTimeout=120 -XX:+UseConcMarkSweepGC -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -Xrs -XX:+UseCompressedOops' \
-e EULA=TRUE -p 25567:25565 --name mc itzg/minecraft-server

As you can see I both have MAX_RAM and -Xmx8G as XX opts. But looking at running process it shows up like this:
![image](https://user-images.githubusercontent.com/7138125/42926618-425eeaea-8b32-11e8-8385-dcd388f9c971.png)

Why is it adding the -Xms1G -Xmx1G when its not specified anywhere in what I ran?

**Comment by tjsd** [comment]
this is from your docker page:
https://hub.docker.com/r/itzg/minecraft-server/
![image](https://user-images.githubusercontent.com/7138125/42945912-eef545c4-8b69-11e8-98c8-42ebc3d8a322.png)

**Comment by itzg** [comment]
Oops, that's a bug of some kind. I just noticed Feed the Beast uses `MAX_RAM`, so I'll either fix the docs in Forge or allow for aliasing that variable with either `MAX_RAM` or `MAX_MEMORY`.

Sorry for the mix up there.

**Comment by itzg** [comment]
I finally realized that since the startup script takes care of translating the `MAX_MEMORY` variable into FTB's, I could remove the misleading content in the README. The new README is now pushed to Docker Hub.
