### ISSUE TITLE
Mincraft - Connection refused while trying rcon

### ISSUE THREAD

**Issue by tjsd** [itzg/dockerfiles#230]
So 3rd issue today :)
When following the documentation and trying to pass a simple command to the running docker I get connetion refused.

![image](https://user-images.githubusercontent.com/7138125/42946617-98b7b3b6-8b6b-11e8-9955-8a30475a9e3a.png)

**Comment by itzg** [comment]
What `TYPE` are you using? It worked with one I launched as follows, but one of the other `TYPE`s might need something fixed.

```
docker run -d --name mc -p 25565:25565 -e EULA=TRUE itzg/minecraft-server
```

**Comment by tjsd** [comment]
This is the same docker as in my previous posts. its a FORGE type.

> docker run -d -it -v /home/minecraft/mc:/data -e VERSION=1.12.2 -e TYPE=FORGE -e FORGEVERSION=14.23.4.2739 -e INIT_MEMORY=1G -e MAX_MEMORY=8G -e PERMGEN_SIZE=512M -e JVM_XX_OPTS='-d64 -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:CompileThreshold=1500 -Xnoclassgc -Xverify:none -XX:UseSSE=3 -XX:+UseThreadPriorities -Djava.net.preferIPv4Stack=true -Dfml.readTimeout=120 -XX:+UseConcMarkSweepGC -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -Xrs -XX:+UseCompressedOops' -e EULA=TRUE -p 25567:25565 --name mc itzg/minecraft-server

**Comment by itzg** [comment]
Weird, the same `docker run ...` worked for me:

```
➜  ~ docker exec -i mc rcon-cli tps
Unknown command. Try /help for a list of commands
➜  ~ docker exec -i mc rcon-cli help
--- Showing help page 1 of 10 (/help <page>) ---/advancement <grant|revoke|test> <player>/ban <name> [reason ...]/ban-ip <address|name> [reason ...]/banlist [ips|players]/blockdata <x> <y> <z> <dataTag>/clear [player] [item] [data] [maxCount] [dataTag]/clone <x1> <y1> <z1> <x2> <y2> <z2> <x> <y> <z> [maskMode] [cloneMode]Tip: Use the <tab> key while typing a command to auto-complete the command or its arguments
```

Can you check in the `mc` container's logs that the RCON listener line popped out at the end, like this:
```
[13:06:41] [Server thread/INFO] [minecraft/DedicatedServer]: Done (16.981s)! For help, type "help" or "?"
[13:06:41] [Server thread/INFO] [minecraft/DedicatedServer]: Starting remote control listener
[13:06:41] [RCON Listener #1/INFO] [minecraft/MinecraftServer]: RCON running on 0.0.0.0:25575
```

**Comment by itzg** [comment]
and if it helps for comparison, this is the generated `server.properties` where I wanted to check things like the `rcon.port`:

```
➜  /tmp cat mc/server.properties
#Minecraft server properties
#Fri Jul 20 13:06:41 GMT 2018
spawn-protection=16
max-tick-time=60000
query.port=25565
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=0
enable-query=false
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=true
level-type=DEFAULT
hardcore=false
enable-command-block=true
network-compression-threshold=256
max-players=20
resource-pack-sha1=
max-world-size=29999984
rcon.port=25575
server-port=25565
texture-pack=
server-ip=
spawn-npcs=true
allow-flight=false
level-name=world
view-distance=10
resource-pack=
spawn-animals=true
white-list=false
rcon.password=minecraft
generate-structures=true
online-mode=true
max-build-height=256
level-seed=
use-native-transport=true
prevent-proxy-connections=false
motd=A Forge Minecraft Server powered by Docker
enable-rcon=true
```

**Comment by tjsd** [comment]
That was it, I already have a server.properties in the folder. So its not generating a new one with the docker. And I did not have rcon enabled there. 

Such a obvious error when I think about it. Sorry!

**Comment by itzg** [comment]
That's ok. There's probably room for improvement in the smartness of the startup script, but for now it leaves the existing properties file alone.
