### ISSUE TITLE
Minecraft - Failing to download 1.13 server

### ISSUE THREAD

**Issue by Kryten0807** [itzg/dockerfiles#231]
I have an existing server which I'm trying to upgrade to 1.13 (released yesterday).

I've backed up my data directory (which is mounted from my Docker host) and deleted the container. Now, when I try to start up my server (using `docker-compose up`), it fails to download the new server version.

Here's the logs:

    server_1  | Switching to user 'minecraft'
    server_1  | Checking version information.
    server_1  | Checking type information.
    server_1  | Downloading minecraft_server.1.13.jar ...
    server_1  | server.properties already created, skipping
    server_1  | Skipping JSON check. No files present.
    server_1  | Setting initial memory to 1G and max to 1G
    server_1  | Error: Unable to access jarfile minecraft_server.1.13.jar
    mc_server_1 exited with code 1

This does **not** result in a minecraft_server.1.13.jar file being added to my data directory.

Upgrading this way has worked in the past.

I notice that it's trying to download minecraft_server.1.13.jar (as opposed to, for example, minecraft_server.1.12.2.jar). It may be that Mojang has mucked around with the format of their `manifest.json` file. I haven't had time to dig into that yet, but I may have time later this evening to look at it. If I do, I'll let you know what I find...

**Comment by itzg** [comment]
I'll try out the upgrade scenario also and see if I can recreate the issue.

**Comment by itzg** [comment]
It might also be a mismatch in directory owner and container uid. With the latest image pulled can you provide the first output line that looks like:

```
Running as '1000:1000' with /data as 'drwxrwxrwx    2 1000     1000          4096 Jul 19 23:31 /data'
```

**Comment by rschellenberg** [comment]
Hello. Very similar issue here, I am unable to download the 1.13.jar file.
Switching to user 'minecraft'
Checking version information.
Checking type information.
Downloading minecraft_server.1.13.jar ...
wget: server returned error: HTTP/1.1 403 Forbidden
Setting initial memory to 1G and max to 1G
Error: Unable to access jarfile minecraft_server.1.13.jar

**Comment by itzg** [comment]
@rschellenberg yes, I'm pretty sure these cases are due to a mismatch in container's uid and the volume's ownership. If it happens again, also check the initial "Running as" log line.

**Comment by chrisb1609** [comment]
I get the same issue. docker logs returns the same log lines for me. I'm not seeing any log lines that say "Running as"

**Comment by chrisb1609** [comment]
Yes. I can post the result of the `docker logs <container>' command, but it looks exactly the same as what was posted by @rschellenberg

**Comment by schemen** [comment]
I can also confirm that I have this now as well! Once home I can provide better logs

**Comment by itzg** [comment]
That’s sounding like something on their end (Mojang or AWS S3) since the response code is definitely coming from the web server. Weird. Does it happen every time or is it sporadic?

**Comment by chrisb1609** [comment]
@itzg It happens to me every time I try to upgrade the container.

To fix, I had to download the jar manually and rename it to `minecraft_server.1.13.jar`

```
[user@minecraft world]# wget https://launcher.mojang.com/mc/game/1.13/server/d0caafb8438ebd206f99930cfaecfa6c9a13dca0/server.jar
[user@minecraft world]# mv server.jar minecraft_server.1.13.jar
```

**Comment by schemen** [comment]
Mh, @itzg It seems the problem was temporary. I do not have any problems anymore.

It indeed seemed to happen everytime for a while, but for now it is resolved on my side.

**Comment by itzg** [comment]
It sounds like this issue has resolved itself and I have also improved the `UID`/`GID` handling of the initial entry script.

**Comment by itzg** [comment]
@jalogisch it's strange how their s3 URL is giving that response to people sometimes. I tried a new container myself just now and it downloaded fine. I'm afraid it's some kind of issue outside the control of the container/image, but still haven't pinned down the pattern of failures.

**Comment by kupiakos** [comment]
I've also had this problem as well. I solved it by manually downloading the jar into the data directory.

**Comment by itzg** [comment]
@Angelinsky7 your scenario does sound similar, but might be a little different too. Issues with not being able to resolve hostnames within the container will be somehow related to the DNS configuration of the container

https://docs.docker.com/config/containers/container-networking/#dns-services

or something that is not quite right with the host's DNS configuration. You could try adding:

```
---dns 1.1.1.1 --dns 1.0.0.1
```

to use Cloudflare's DNS servers.

**Comment by TheNotary** [comment]
This seems related to #307, I'm having trouble booting this correctly on my K8s cluster, and I'm not sure how to specify DNS for them.  I'm going to start fiddling around with the docker container to see if I can work around it via unix tricks.

**Comment by TheNotary** [comment]
Actually, in my case, I didn't have any networking at all because I couldn't even ping `8.8.8.8`.  I solved the problem by running `sudo iptables -P FORWARD ACCEPT` on the microk8s host.
