### ISSUE TITLE
Server ignoring my prefs...

### ISSUE THREAD

**Issue by macmattias** [itzg/dockerfiles#233]
I use this to start the server:
docker run -d -v /media/storage/minecraft:/data -it -e EULA=TRUE -e OPS=HerrPlayer -e MAX_PLAYERS=10 -e ANNOUNCE_PLAYER_ACHIEVEMENTS=true -e HARDCORE=false -e MODE=creative -e 'Our server for us by us, you are not welcome' -p 25565:25565 --name serverco itzg/minecraft-server

It starts just as it should, but all is at default. What am I doing wrong?

**Comment by macmattias** [comment]
Please remove this non error. Was me being stupid.

**Comment by itzg** [comment]
Glad you worked it out :)
