### ISSUE TITLE
Where are the server files saved by default?

### ISSUE THREAD

**Issue by chillycurve1** [itzg/dockerfiles#237]
I apologize if this is an easy question, I am relatively new to docker.

I have done everything I know to do and still cannot find the working directory of this container. Here is the relevant section of my docker-compose:

``` 
minecraft-server:
    ports:
      - "25565:25565"
    container_name:  mc
    environment:
      EULA: "TRUE"
      VERSION: "1.12.2"
      TYPE: "FORGE"
      FORGEVERSION: "14.23.4.2739"
      DIFFICULTY: normal
      OPS: "ChillyCurve_, ChillyCurve"
      ALLOW_NETHER: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      GENERATE_STRUCTURES: "true"
      SNOOPER_ENABLED: "false"
      MAX_TICK_TIME: "60000"
      SPAWN_MONSTERS: "TRUE"
      VIEW_DISTANCE: "25"
    image: itzg/minecraft-server
    container_name: mc
    tty: true
    stdin_open: true
    restart: always
    volumes:
        - ${USERDIR}/docker/mc:/data
        - ${USERDIR}/docker/mc/plugins:/plugins
        - ${USERDIR}/docker/mc/config:/config
        - ${USERDIR}/docker/mc/mods:/mods
    labels:
       - "traefik.enable=false"```


Thank you in advance!

**Comment by itzg** [comment]
The working directory within the container is `/data`, so with your volume definition:

```
        - ${USERDIR}/docker/mc:/data
```

the server files should be located on your host in `${USERDIR}/docker/mc`.

**Comment by chillycurve1** [comment]
Thank you for your reply. That is where I expected it to be, as all my other containers are there, but it just isn't there. 

![image](https://user-images.githubusercontent.com/37170946/43437770-645f6846-9450-11e8-8b89-cf23fc71f97b.png)

Any ideas?

**Comment by itzg** [comment]
No ideas off hand since I would have expected to see it there two. Perhaps try just the `/data` attachment.

**Comment by chillycurve1** [comment]
Thanks for your help. I replaced the volume section with a single volume for the entire container and it worked. 

Solved!

**Comment by itzg** [comment]
Glad to hear since I have wasn’t able to recreate the issue using similar volume entries.
