### ISSUE TITLE
Minecraft - Move ownership to startup

### ISSUE THREAD

**Issue by ekristen** [itzg/dockerfiles#239]
First, thanks for the wonderful and very complete image, it is well done and works well.

Setting ownership to 1000:1000 at image build time raises issues with using external volume providers. I believe it would be beneficial to move the setting of ownership defined at https://github.com/itzg/dockerfiles/blob/master/minecraft-server/Dockerfile#L25 to the startup scripts.

When using an external volume like something from the host, or glusterfs, amazon, or anything else, you start to run into issues with the default uid/gid set to 0 or 0 and a random number, but since the container starts as root and then starts minecraft as 1000:1000 it would be more beneficial to during startup to set all the volumes to the user 1000:1000.

Alternatively move this https://github.com/itzg/dockerfiles/blob/master/minecraft-server/Dockerfile#L22-L25 to the startup script so you could make the UID/GID settable via environment variables.

**Comment by itzg** [comment]
Just in the past couple commit I actually restored the ability to adjust the runtime user via the `UID` and `GID` variables

https://github.com/itzg/dockerfiles/blob/master/minecraft-server/start

It also turns out the chown in the Dockerfile is not honored by external volume providers, so setting the runtime user to match the established volume ownership is the best/only solution.

**Comment by ekristen** [comment]
Correct it is not honored. However I still think the best bet would be to add a chown -R $UID:$GID just before the su-exec to all the defined volume mounts because unless the volume driver is specifically design to allow you to change the GID, generally the volumes will get mounted in as 0:0. 

Since the container initially run's as root just before the su-exec you can call a recursive chown to ensure proper ownership of all directories needed regardless of how the content makes it in.

**Comment by itzg** [comment]
Good point. I was actually pondering reviving that feature also, so you have helped me decide :)

**Comment by ekristen** [comment]
Awesome, glad I could help!

**Comment by mumbley** [comment]
I added an init container to the container spec in the stable/minecraft helm chart.  This fixed the issue.  I can send it as a MR if you like? @itzg

**Comment by itzg** [comment]
@mumbley that would be great to integrate that into the image here for non-k8s scenarios.

**Comment by itzg** [comment]
This is now pushed to Hub.
