### ISSUE TITLE
ServerStart.sh is not being run in bash

### ISSUE THREAD

**Issue by Todapie** [itzg/dockerfiles#240]
When I run the ServerStart.sh outside of the container using sudo bash StartServer.sh it seems to run but not in the container for some reason.

Checking version information.

ecking type information.

Looking for Feed-The-Beast server modpack.

server.properties already created, skipping

Skipping JSON check. No files present.

Setting initial memory to 1G and max to 1G

Running FTB server modpack start ...

Please do not use sh to run this script (/data/FeedTheBeast/ServerStart.sh). Use bash instead (or execute it directly)

2018/08/12 14:30:46 Done

usermod: no changes

Running as '1001:1001' with /data as 'drwxr-xr-x    8 1001     1001          4096 Aug 12 14:30 /data'

Also  when the container downloads the modpack it puts it in a top level folder and thus I had to unpack it into the FeedTheBeast directory manually, not sure if this is something you would want to address.

**Comment by itzg** [comment]
I’m not quite understanding the scenario. Can you provide the exact “docker run” command you’re using and then the commands within the container?

**Comment by Todapie** [comment]
![env](https://user-images.githubusercontent.com/12718503/44005171-fb940c30-9e3c-11e8-9469-cb8badbfa8d2.PNG)

I use portainer here are the env variables that are set for the container. There is also a data volume and it's named minecraftServer.

**Comment by itzg** [comment]
That helps, but I'm not able to recreate the problem running the container normally with `TYPE=FTB` and using the same `FTB_SERVER_MOD`. Are you saying you're manually invoking the FTB start script within the container?

**Comment by itzg** [comment]
I spoke too soon -- my docker compose environment must have been caching something since launching via `docker run` has hit a similar, but slightly different failure:

```
Skipping JSON check. No files present.
Setting initial memory to 1G and max to 1G
Running FTB server modpack start ...
sh: can't open '/data/FeedTheBeast/ServerStart.sh': No such file or directory
2018/08/12 19:28:40 Done
```

**Comment by Todapie** [comment]
Yeah sorry I kinda mentioned two errors at once without providing the outputs for the second.

So basically there are two errors there the first being the one you just ran across that the ServerStart.sh script won't exist until you move it into the /data/FeedTheBeast/ directory. I am also not sure if the whole entire server zip is supposed to be unzipped into this location as well.

The second error is that the ServerStart.sh file seems to be only runnable in /bin/bash due to this section of the file.

```
# Make sure users aren't trying to run script via sh directly (won't work)
if [ ! "$BASH_VERSION" ] ; then
    echo "Please do not use sh to run this script ($0). Use bash instead (or execute it directly)" 1>&2
    exit 1
fi
```

Even with this section of code missing the file will crash when run.

```
/data/FeedTheBeast/ServerStart.sh: line 61: syntax error: unexpected "(" (expecting "then")
```

I am not able to get inside and attach to the container in because it immediately crashes so I am not sure if running this file with 

```
sudo bash ServerStart.sh
```

will work inside the container, but I have tried it inside the data volume and this command seems to work. I have noticed that your start-minecraftFinalSetup seems to be where the ServerStart.sh file is called and am just not sure why this would not call it in bash do to the #!bin/bash but I also do not understand how the command you are running works, or really need to know, but hope this info/description helps.

https://github.com/itzg/dockerfiles/blob/7005f00df0fc3051d189ae141859921097610529/minecraft-server/start-minecraftFinalSetup#L98

**Comment by itzg** [comment]
Should be fixed in d9c2f265061d6d897bd813f458414cf8d455e53d and now building in Docker Hub

**Comment by itzg** [comment]
BTW, thanks for the further analysis. The mystery part was the fix I had to make in the process wrapper at https://github.com/itzg/mc-server-runner/commit/fde5a96925eddcbff60880040205e0fe5ea75bb3

**Comment by itzg** [comment]
...and now pushed to Hub. @Todapie can you give it a try now?

**Comment by Todapie** [comment]
No problem man I was just trying to make sure it wasn't something on my side and was hoping it might be helpful.

Also yeah I just pulled and it looks like it is running... no idea if it will be enough for me to actually connect but it definitely got past that error thanks
