### ISSUE TITLE
Paper 1.13 server different url

### ISSUE THREAD

**Issue by dehein** [itzg/dockerfiles#244]
Hi. The Paper jenkins server is using a different url scheme for the latest server builds:

Dont know how to integrate it, but it should look something like this.

also they don't support the version=1.13 option because the build versions are numbered after each other not relating to minecraft version.

https://destroystokyo.com/ci/job/Paper-1.13/lastSuccessfulBuild/artifact/paperclip.jar

**Comment by itzg** [comment]
@dehein the fix for this is now pushed to Hub. Thanks for reporting the issue.
