### ISSUE TITLE
Minecraft - Clone world folder

### ISSUE THREAD

**Issue by Stumblinbear** [itzg/dockerfiles#247]
In the Minecraft server Dockerfile, I'd appreciate it if it was possible to instruct the container to clone the supplied world directory on startup. Currently, to make "read only" worlds, I have a plugin that instructs the world to not save itself, but this is unfortunately not fool proof, as save commands and plugins forcing a world save cause the files to be written to. It also creates the session.lock file which prevents other containers from loading the world as well.

Use case: multiple containers using a single read-only world in a PvP or Minigame server. 

Is this in the scope of this Dockerfile, or do you suggest I clone it and add it myself?  Perhaps there's a way to run a command to clone the folder before the server is booted up?

**Comment by itzg** [comment]
If I understand the scenario correctly, it does seem like that's something the Dockerfile, or more specifically, the startup scripts could manage.

To ensure I understand, you're wanting to have a pristine or baseline copy of a world directory and then when creating a new container have it clone (or copy) that baseline copy into the `/data/world` directory where that container will operate on the world files like normal?

If that's the case, then I could see the startup detecting the presence of a `/world` path and use as that the source of the clone operation on startup.

**Comment by Stumblinbear** [comment]
Yes that's exactly what I mean. I started putting together an endpoint for downloading the world zip from the API, but if this was supported in the Dockerfile that would be amazing.

**Comment by itzg** [comment]
Sorry for the delay on this @Stumblinbear . I'm about to push an update that will enhance the existing `WORLD` option to let it not only download from a URL but also clone from a directory that exists within the container as described in this new section:

https://github.com/itzg/dockerfiles/tree/master/minecraft-server#cloning-world-from-a-container-path

**Comment by itzg** [comment]
...it's now available on Docker Hub.
