### ISSUE TITLE
Minecraft - GID not picked up by start script

### ISSUE THREAD

**Issue by hotchkj** [itzg/dockerfiles#254]
I may be doing something terribly wrong, as I'm fairly new to Docker and usually manage to get subtleties of Linux permissions upside down :wink: but I've got the following situation, and `GID` doesn't seem to map properly as per instructions. Any advice appreciated as to what I might be doing wrong.

Environment: Synology NAS (which has its own 'unique' ideas about UID & GID handling, I discovered)
An existing restricted user on the host 1027:100 called `minecraft` and `users` respectively.

Image: Latest as of 27th Sept 2018
Mounting: `docker/minecraft:/data:rw`

Env variables set:
- `UID`: 1027
- `GID` 100
- `PUID`: 1027
- `PGID` 100

(I came across instructions that recommended the P prefixes as well but this might be cargo-culting).

The Minecraft server would start up with:
```
groupmod: GID '100' already exists
Running as uid=1027 gid=1000 with /data as 'drwxrwxr-x    1 1027     100            128 Sep 30 10:11 /data'
```

The mapped volume would have all its data on the host written as user `minecraft` and GID `1000` and be inaccessible by normal users.

I hacked the `start` script as follows to fix it up temporarily, but I'm curious to know if this is a bug or I should have configured the system differently to get the script to work and map the data written by the container to permissions the host understands:

``` bash
#!/bin/bash

umask 0002
chmod g+w /data

if [ $(id -u) = 0 ]; then
  if [[ -v UID && $UID != $(id -u) ]]; then
    usermod -u $UID minecraft
  fi
  if [[ -v GID ]]; then
    usermod -a -G $GID minecraft
  fi

  if [[ $(stat -c "%u" /data) != $UID ]]; then
    echo "Changing ownership of /data to $UID ..."
    chown -R minecraft:$GID /data
  fi

  exec su-exec minecraft:$GID /start-configuration
else
  exec /start-configuration
fi
```

Thanks in advance for any assistance!

**Comment by itzg** [comment]
Ah, you were on to the right solution. I found that `groupmod` had an option to force a non-unique use of GID=100 (in this case). Can you pull the latest fix and see if that resolves it for you?

**Comment by hotchkj** [comment]
Looks to be solved! Thanks very much for the quick turnaround & for maintaining these great utilities.
