### ISSUE TITLE
Minecraft-server stopped unexpectedly

### ISSUE THREAD

**Issue by daoyuanjiao** [itzg/dockerfiles#261]
I downloaded (https://hub.docker.com/r/itzg/minecraft-server/) in the Docker in dsm3617 of Synology, and after installation, it always shows "Minecraft-server stopped unexpectedly." ！ What other settings does it need? Thank you!
![tim 20181025133758](https://user-images.githubusercontent.com/20084531/47478475-035fc900-d85c-11e8-873c-b4e92e36cacf.png)
![tim 20181025140049](https://user-images.githubusercontent.com/20084531/47479153-ae718200-d85e-11e8-8488-259c73c47a5c.png)

**Comment by itzg** [comment]
Hi @daoyuanjiao , your screenshot actually highlights the solution. The container does require the environment variable `EULA` to be set to the value `TRUE`.

**Comment by daoyuanjiao** [comment]
I have now set the EULA setting to True. But when I log in, I see the following image:
![tim 20181026175707](https://user-images.githubusercontent.com/20084531/47559628-92e2a600-d948-11e8-8506-309352548b8b.png)
![tim 20181026175910](https://user-images.githubusercontent.com/20084531/47559743-e05f1300-d948-11e8-8f32-48d89bd0b06f.png)

**Comment by daoyuanjiao** [comment]
I reboot and show the following picture
![tim 20181026183511](https://user-images.githubusercontent.com/20084531/47561491-f91df780-d94d-11e8-9e83-0b80bb3eabce.png)
[10:33:22] [Server thread/INFO]: com.mojang.authlib.GameProfile@4f0ffdb3[id=<null>,name=daoyuanjiao,properties={},legacy=false] (/172.17.0.1:45757) lost connection: Disconnected

**Comment by daoyuanjiao** [comment]
Sorry, it's my own setup problem!

**Comment by itzg** [comment]
Thanks for the update.
