### ISSUE TITLE
MC server time 

### ISSUE THREAD

**Issue by haudankaivajasi** [itzg/dockerfiles#263]
Hi,

I have encountered a problem with the server time. Is there a way to make it follow the system time?
I have used the following line in a few other containers and it seems to be working in them but not on this one.
-v /etc/localtime:/etc/localtime:ro

 Is there any way to fix this?

**Comment by itzg** [comment]
...oh, it's regarding the timezone? I thought you meant the clock itself gets out of sync from the host. It looks like I might need to be adding the `tzdata` package for it to work as you expect:

https://wiki.alpinelinux.org/wiki/Setting_the_timezone

**Comment by itzg** [comment]
This fix is now pushed to Docker Hub. Let me know if this still doesn't resolve the issue for you.

**Comment by itzg** [comment]
Yeah, when testing the before and after I confirmed it was using UTC previously. 

Yes, the container has to be recreated unfortunately to pick up a new image; however, if you have `/data` and such attached via volumes then it is safe to recreate the container.

**Comment by haudankaivajasi** [comment]
Ok cool.
Pulled the new image and I'm restarting the server atm. The time in the console seems to still be 2 hours late :o should it be fixed or do I need to add another parameter or something?

**Comment by itzg** [comment]
Hmm, no, the mounting of `/etc/localtime` like you had before should do it.

**Comment by itzg** [comment]
To sanity test, can you try

```
docker pull itzgminecraft-server
docker run --rm -v /etc/localtime:/etc/localtime --entrypoint date itzg/minecraft-server
```

compared to

```
docker run --rm --entrypoint date itzg/minecraft-server
```

**Comment by haudankaivajasi** [comment]
I ran the suggested lines and the first did return the correct date and time. but the latter and  when I create the server container, the time seems to be still off. The command I use is as follows:

> docker run -d -v /share/CACHEDEV1_DATA/Container/container_files/Minecraft:/data \
    -v /etc/localtime:/etc/localtime:ro \
    -e TYPE=FTB \
    -e FTB_SERVER_MOD=https://www.feed-the-beast.com/projects/ftb-infinity-evolved/files/2484486 \
    -e MEMORY=2G \
    -p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server

**Comment by itzg** [comment]
Thanks for running the sanity test commands -- your system definitely has and is running the updated image as I'd hope. It's then strange the real FTB container is not honoring the timezone setting for you. I ran a stripped down version of your command 

```
docker run -it --rm \
    -v /etc/localtime:/etc/localtime:ro \
    -e TYPE=FTB \
    -e FTB_SERVER_MOD=https://www.feed-the-beast.com/projects/ftb-infinity-evolved/files/2484486 \
    -p 25565:25565 -e EULA=TRUE itzg/minecraft-server
```

and it did properly convey the local timezone for me at least:

![screenshot from 2018-12-09 21-47-54](https://user-images.githubusercontent.com/988985/49709985-72229700-fbfc-11e8-978f-5ed314fb6b17.png)

**Comment by haudankaivajasi** [comment]
Yeah, really strange. I'll try to create the container again and see if it works then.
My time zone is gmt+2 so I have no idea why it won't respect that although other containers do.

**Comment by haudankaivajasi** [comment]
Yeah, really strange. I'll try to create the container again and see if it works then.
My time zone is gmt+2

**Comment by lunarys** [comment]
In case someone is still looking for a solution to this issue: 
The server will use the correct timezone if it is explicitly set for the JVM.
So for me this is: `-Duser.timezone="Europe/Berlin"`, 
which can be set in this image with `--env JVM_DD_OPTS=user.timezone="Europe/Berlin"`
