### ISSUE TITLE
INIT_MEMORY and MAX_MEMORY on helm

### ISSUE THREAD

**Issue by scones** [itzg/dockerfiles#273]
Hey itzg,

i'd report this issue on the helm repo (and fix it) but the helm repo guys alsways expect the extra effort of cloning, writing patch notes, filling out a bunch of form, selling one's grandparent, declaring peace in [select disputed country] and the such.

The core issue is quite simple:
`INIT_MEMORY`and
`MAX_MEMORY` are missing in the deployment yaml as environment variables (and of course in values), thus making it hard to setup a (you guessed it) FTP-Server.

best regards,
scones

**Comment by itzg** [comment]
Yes, I have definitely noticed some projects/repo are much stricter with contributions than others; however, the primary helm charts have a lot of visibility, so the strictness is warranted.

I took a quick look at the [deployment yaml](https://github.com/helm/charts/blob/master/stable/minecraft/templates/deployment.yaml) as you mentioned hoping to find a nice, generic hook to add more environment variables...but there's not.

I see a couple of options:
- Submit a PR that is effectively a follow up to https://github.com/helm/charts/pull/8025 adding the two FTB memory related variables
- I could establish a helm repo dedicated to this Minecraft image; however, that would negate the excellent contribution so far of the Minecraft helm chart

I'm leaning towards the first option. You're welcome to kick off that PR and tag me or I can try driving that PR.

**Comment by scones** [comment]
oh, sorry, i was under the impression you added that (as it is your image used there).

nevermind then. i will go the long way then :/
