### ISSUE TITLE
Building a Forge mod image on top of this one?

### ISSUE THREAD

**Issue by altano** [itzg/dockerfiles#276]
I'm trying to build an image for a Forge mod, [The Simple Life 2: Genesis](https://minecraft.curseforge.com/projects/the-simple-life-2/files/2643674), on top of yours and I'm having trouble. Would you by any chance be willing to help?

My image is up at [altano/simple-life-2:latest](https://cloud.docker.com/repository/docker/altano/simple-life-2) and the Dockerfile is simply:

```
FROM itzg/minecraft-server:latest

EXPOSE 25565

WORKDIR /data

ADD TSL2_Server_Files_2.3.tar.gz /data

ENV TYPE FORGE
ENV FORGEVERSION 12.18.3.2511
ENV VERSION 1.10.2
ENV MOTD='A Simple Life 2 Minecraft Server powered by Docker'
```

`TSL2_Server_Files_2.3.tar.gz` contains the server pack repackaged to be a tgz, have all the files at the root, and the .jars removed.

If I run this image with `docker run -e EULA=true -e INIT_MEMORY=1G -e MAX_MEMORY=5G -p 25565:25565 -it --rm altano/simple-life-2:latest` the server appears to be starting up but will terminate without error:

> [14:08:05] [Server thread/INFO] [fluxnetworks]: Finished Pre-Initialization
> 2018/12/31 14:08:30 Done

It doesn't always terminate at the same place, but it always terminates. I'm not sure how to diagnose this any further since I can't find any way to get more verbose logging. =\

Any help would be most appreciated. Thanks for this awesome image!

**Comment by altano** [comment]
FWIW I can't get this to work either so I must just be doing something really dumb:

```bash
docker run \
  -e EULA=true \
  -e INIT_MEMORY=4G \
  -e MAX_MEMORY=10G \
  -e TYPE=FTB \
  -e FTB_SERVER_MOD=https://www.feed-the-beast.com/projects/ftb-revelation/files/2637817 \
  -p 25565:25565 \
  -it \
  --rm \
  itzg/minecraft-server
```

This server dies during startup too:

> [14:47:20] [Server thread/INFO] [FML]: Disabling mod thaumicjei it is client side only.
> /data/FeedTheBeast/ServerStart.sh: line 27:   125 Killed                  "$JAVACMD" -server -Xmx${MAX_RAM} ${JAVA_PARAMETERS} -Dfml.queryResult=confirm -jar ${FORGEJAR} nogui
> 2018/12/31 14:47:36 Done

**Comment by altano** [comment]
OOoh one more piece of in formation:

When using `docker-machine` to execute these commands against my Ubuntu Server docker host, the containers start with no issues. They are just failing on my local Docker for Windows client. I can't imagine why there's a difference? Hmmm....

**Comment by altano** [comment]
Ooookay I figured this out: Docker Engine on Windows defaults to 2GB of RAM being allocated. Increasing this to 6GB of RAM fixed everything and now I can start my Minecraft servers.

I guess the solution to all Minecraft problems continues to be the same: find somewhere to increase a RAM allocation. =\

Sorry for the noise and thanks again for this excellent image! :)

**Comment by itzg** [comment]
No problem at all and glad to hear you figured it out. Yes, increasing the VM memory has become my standard procedure for Docker for Desktop :) .
