### ISSUE TITLE
whitelist.json

### ISSUE THREAD

**Issue by altano** [itzg/dockerfiles#277]
I see that you can specify a set of names in the whitelist environment variable during initial configuration, but that only lets you specify names (not the UUIDs like whitelist.json). Is there an easy way of specifying a list of UUIDs instead of names (which aren't guaranteed unique) when configuring the server? Can the environment variable take UUIDs instead of usernames?

**Comment by Queuecumber** [comment]
Does whitelist.txt even do anything anymore? Everything I'm reading makes it sound like only the .json that requires a UUID is used on modern versions

**Comment by altano** [comment]
Not sure what you mean, @Queuecumber? What is whitelist.txt? I'm only familiar with the WHITELIST environment variable and the whitelist.json. I have a whitelist.json file, I'm just not sure the best way to get it onto the server (especially with docker compose).

**Comment by altano** [comment]
> And to answer your second question, it should work to just copy your whitelist.json into the /data folder

How tho? :) This just creates a whitelist.json directory, inexplicably:

```
volumes:
      - ./minecraft/config/whitelist.json:/data/whitelist.json:ro
```

**Comment by itzg** [comment]
@altano the volume attachment of `/data/whitelist.json` should have worked, but also make sure you're **not** setting `WHITELIST` in this case. Otherwise the startup will overwrite the json content with the `white-list.txt` populated behind the scenes.

Yes, @Queuecumber , the `white-list.txt` trick still works as of 1.13.2, which like you said is what the container startup script uses given the `WHITELIST`.

**Comment by altano** [comment]
1. I didn't realize Docker Machine doesn't copy local files automatically over when running Docker Compose. whitelist.json just didn't exist on the host so it was getting created as a directory. I will move my configuration files into an NFS share and mount from there and not reference anything locally. Mystery solved!
1. I didn't realize Minecraft usernames were unique. Your image's way of setting the whitelist via environment environment variable seems totally enough for me now and I don't need the whitelist.json :)

Thanks for the help both of you.
