### ISSUE TITLE
WORLD restore/clone doesn't work with FTB

### ISSUE THREAD

**Issue by altano** [itzg/dockerfiles#278]
The WORLD restore/clone feature seems to work just fine, but when using FTB it clones the world into the /data root directory and not the /data/FeedTheBeast directory. So the end result was:

```
/data
   /restored-world   <==== this is what was cloned from my volume
   /FeedTheBeast
      /restored-world <==== this is a new world and what is actually being used
```

**Comment by itzg** [comment]
I was a little worried about that possible behavior when I wasn’t researching your other question. Thanks for reporting this.

**Comment by itzg** [comment]
@altano I pushed that update that should fix this. Can you try after pulling the latest?

**Comment by altano** [comment]
Well that worked. Thanks for fixing that so quickly. You sir are awesome.
