### ISSUE TITLE
CurseForge modpacks don't get the correct ram params

### ISSUE THREAD

**Issue by raxkin** [itzg/dockerfiles#285]
For example this mod: https://minecraft.curseforge.com/projects/enigmatica2expert/files/2663151#additional-files

When i run the server like the documentation and using the ram param, it don't have any effect.

```
docker run ... \
  -e MAX_MEMORY=10G
  -e TYPE=CURSEFORGE \
  -e CF_SERVER_MOD=https://minecraft.curseforge.com/projects/enigmatica2expert/files/2663153/download
```

It will start the server with 4G. This 4G is configured by default by the modpack on the `settings.cfg` file.
Changing the value in that file manually works fine.

Maybe it have the same problems with other configs defined in that file

**Comment by raxkin** [comment]
Maybe related with #271

**Comment by itzg** [comment]
Yes, it probably is related. The FTB/CurseForge packs seem to keep changing the way the JVM parameters are passed, so I’ll see what they’re doing in this case and adapt the startup script.

**Comment by itzg** [comment]
This change has been pushed to Docker Hub. I have tested it to work with the Enigmatica 2 modpack and hopefully it will work with others that set the max memory similarly.
