### ISSUE TITLE
CurseForge manifest support

### ISSUE THREAD

**Issue by dudymas** [itzg/dockerfiles#287]
So, I have a script I run locally that will, given a manifest.json, download files from curseforge and put them into the mods folder. It just runs a jq script to create the download urls and runs curl on them. The results are put in /data/mods as 'fileID.jar', where 'fileID' is the download file id (some modpacks don't add info on which jar is which, so I do this to avoid clobbering jar files, and if the modpack changes, I just delete the mods dir and redo this process).

This came about from people making client-only modpacks and I just wanted to quickly make a server by dropping a ServerStart.sh and settings.cfg into the `FeedTheBeast` dir and just run with things.

I've found this handy enough that I thought I'd volunteer to make a PR to support the following:

Given
- `MANIFEST_DOWNLOAD` env variable is set
- `TYPE=CURSEFORGE`
- `CF_MODPACK_MOD=Some_valid_url_to_a_modpack`
- the modpack has a manifest.json under the 'FeedTheBeast' dir with a 'files' entry that details `projectID` and `fileID` pairs

Then
- the itzg/minecraft-server docker entrypoint should essentially download each file, naming it `fileID.jar` in `/data/mods`

So far this works fine for me, and makes upgrades a snap. I just re-run the server entrypoint with the refresh mods env var set whenever I need to clear things out... and if I need to accept changes, I add the `-it` to the `docker run` command and respond to blockid prompts until my `world` is happy.

If this proposal sounds dandy, I can make a PR in the next couple days (I'll update readme, add the script as a function in `start-deployFTB` and all that jazz) and see what you think. Naturally, I don't want to make a PR if you're not interested. I'm fine running this manually on my servers, and just thought you might find it helpful.

**Comment by itzg** [comment]
Yes, this sounds very interesting. The motivation seems to be fairly similar to the contribution in PR #267 ; however, your proposal attacks a slightly end goal and dynamically at server startup. I think a PR, even if just in a "draft" form would be a great way to explore further what you are proposing.

**Comment by itzg** [comment]
I was thinking about this some more and was wondering how your approach relates to being able to download and use their provided server modpacks such as

```
-e TYPE=CURSEFORGE -e CF_SERVER_MOD=https://minecraft.curseforge.com/projects/sevtech-ages/files/2570735/download
```

**Comment by dudymas** [comment]
So, looking at sevtech, I don't see a manifest.json so I would assume my change doesn't apply to something like that project. If the mods are already populated, no problem.

**Comment by dudymas** [comment]
Basically, this is only helpful for people who make their own private modpacks. The flow from https://authors.curseforge.com/knowledge-base/minecraft/120-minecraft-modpack-submission details that a manifest.json is used for all mods hosted in curseforge, rather than the actual jar files. As such, big name modpacks will likely not have this.

**Comment by itzg** [comment]
Thanks, that clarifies a bunch for me. As you can probably tell, I don't personally use CurseForge modpacks (nor Feed the Beast), so I'm quite ignorant of the coolness there. With this new information, I agree it sounds like your solution is attacking a unique problem within the image.

**Comment by dudymas** [comment]
I've posted a PR for this at https://github.com/itzg/dockerfiles/pull/289
I'll try to find an example public modpack (the ones I use this on are private) and you can try it out.

I ultimately could have added env vars for ServerStart.sh and settings.cfg (since frankly, settings.cfg can be generated by manifest.json), but the effort would likely break the rules of https://xkcd.com/1205/
