### ISSUE TITLE
Mc auto restart after crash

### ISSUE THREAD

**Issue by wuast94** [itzg/dockerfiles#290]
is it possible to auto restart the mc server when its crashed? i use a forge mod server in mineos now. and there is the problem that when the server crashes (it do it sometimes :D) it dont start again and the webui do not response then. 

so is it possible to do that on your docker container ? auto restart when crash ?

**Comment by r3Fuze** [comment]
This is built into Docker. Here are the docs for it: https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by itzg** [comment]
I agree with @r3Fuze , you'll want to use the built-in Docker mechanisms for auto-restart of containers. In addition to the link provided, here's the equivalent for Kubernetes: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy
