### ISSUE TITLE
Build Java memory issue

### ISSUE THREAD

**Issue by Kianda** [itzg/dockerfiles#292]
Hi I think I've found an issue inside the file "start-deployBukkitSpigot".
On my VPS (1GB RAM + 1GB SWAP) the build inside the function:

'function buildSpigotFromSource'

will return the error:

'BuildTools requires at least 512M of memory to run (1024M recommended), but has only detected xxxM'

because on the command:

'java -jar /data/temp/BuildTools.jar --rev $VANILLA_VERSION'

there is no '-Xmx1024M' option like:

'java -Xmx1024M -jar /data/temp/BuildTools.jar --rev $VANILLA_VERSION'

If this fails then it will throw later on the error 'Error: Unable to access jarfile spigot_server.jar'

I think you should add the Xmx and Xms values from the MEMORY environment variable (from the docker run command) inside all the build functions (and fallback to 1024M if missing)

What do you think?
Thanks!

**Comment by itzg** [comment]
That’s a good idea. It might be a couple of days before I can get to this so you’re welcome to contribute a PR too.

**Comment by itzg** [comment]
The fix is now available on Docker Hub.
