### ISSUE TITLE
mc server very high I/O

### ISSUE THREAD

**Issue by wuast94** [itzg/dockerfiles#297]
I have a very strange issue. 

My server run on a docker image in unraid. from this server the ram gets full and the system lags very hard overall. so thats normal for me anyway. 

But what i dont understand. on the ssd was continusly max read traffic. in the moment i stopped the mc server it stops. so why does the minecraft server maxed out the disk I/O ? 
![Screenshot_2019-03-20 Server Stats](https://user-images.githubusercontent.com/16965460/54719361-f7eba200-4b5c-11e9-8b4e-aafed9588bfe.png)
you see the moment i stopped the mc container. i looked into logs but i cant see anything.

**Comment by itzg** [comment]
The issue likely has nothing to do with running within Docker, but I’m curious to help out. My first suspicion was that the system has started using swap after exhausting RAM; however, I believe that would show a mix of write and read I/O. 

Do the container/server logs report any ongoing messages?

What configuration are you using for the container?

**Comment by wuast94** [comment]
Yes that was what I'm thinking too but as you said..only read. 

I checked the logs from unraid..docker...and container/Mc..but nothing...

My config is attached in picture: 
![F2DA4B7C-11AC-4565-A6A2-71340241BD97](https://user-images.githubusercontent.com/16965460/54754906-f49bf900-4be4-11e9-998e-0218be7a9a27.png)

The args (the field is not long enaugh in picture: : -Dfml.queryResult=confirm -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch

**Comment by wuast94** [comment]
One thing but shouldn't be the problem..I changed one thing in your docker file..I switched from image jre to jdk for extra arguments.

**Comment by itzg** [comment]
Yeah the switch to JDK shouldn’t make a difference. Can you also provide the Docker env settings?

**Comment by wuast94** [comment]
In the picture are all of the env settings :)

**Comment by itzg** [comment]
Sorry, I was looking for a particular FTB or CurseForge pack since those tend to be resource intensive. Now I see you're using a custom forge setup. It'll be tedious but trying different combinations of mods or at least no mods at all to see how the baseline forge server behaves might help narrow down the problem.

**Comment by wuast94** [comment]
Im using the Projekt ozone 3 mod pack. 
To reproduce this I need something to make my Ram full :D 

But I'm testing a bit this week and tell you more then :)

**Comment by wuast94** [comment]
I can't repuduce this issue.. So I close it and hope it will never come again
