### ISSUE TITLE
[Feat]: dynamic replacement of variables with environment variables

### ISSUE THREAD

**Issue by Silthus** [itzg/dockerfiles#298]
I recently finalized my ready to start docker image (#218) and came accross one more issue. I have a lot of config files that use database connection strings and such. Actually I think most minecraft server owners have at least one file that contains database informations.

Now we could include the connection string when building the image but then sensitve information would be out there in the wild. Also it is Docker best practice to use environment variables or even better secrets to provide sensitve information to docker containers.

I then had the idea of going thru all of the config files and replacing predefined variables with environment variables. Lets take the following example.

We have a `config.yml` file somewhere burried deep inside the `/data/plugins/` directory.

```yml
...
database:
    host: ${CFG_DB_HOST}
    name: ${CFG_DB_NAME}
    password: ${CFG_DB_PASSWORD}
```

All of these variables will be replaced automatically by environment variables defined in your container.

```docker-compose
version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "mc:/data"
    environment:
      EULA: "TRUE"
      CONSOLE: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
      # define an optional prefix for your env variables you want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # and here are the actual variables
      CFG_DB_HOST: "http://localhost:3306"
      CFG_DB_NAME: "minecraft"
      CFG_DB_PASSWORD: "ug23u3bg39o-ogADSs"
    restart: always
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"

volumes:
  mc:
  rcon:
```

After your server started all configs that contain the prefix variables wrapped inside `${...}` will be replaced with the given values.

**Comment by itzg** [comment]
This is a fantastic idea and I like it even more since you have the PR mostly done :)

**Comment by Astronautikus** [comment]
I've just added some of those enviroment variables (e.g. level_name=${CFG_LEVEL} )to /data/server.properties but it is not working as expected.
When I start the server, the variables in the file /data/server.properties get overwritten by the actual values - so my example is changed to level_name=minecraft-fun.
So this "feature" is only usable once because now the variables are replaced by real values again.
I'd expect the variables to stay there so I just can set the values in docker and don't have to touch server.properties again.
Have I understood that feature wrong or is is not working on my end?

**Comment by itzg** [comment]
@Astronautikus please try to avoid adding a comment to an issue closed almost 2 years ago. Yes, you have misunderstood the feature. You will instead want to read this section, which includes an option to override the server.properties on every startup:

https://github.com/itzg/docker-minecraft-server#server-configuration
