### ISSUE TITLE
minecraft-server: MOTD not overriding the server MOTD

### ISSUE THREAD

**Issue by timvisher** [itzg/dockerfiles#30]
Thanks so much for the docker container!

When I start the container like this:

```
docker run -d -it -p 25565:25565 --name mc -e EULA=TRUE -v ~/minecraft-data:/data -e ICON=<some-image> -e 'MOTD=An Overriden Message' itzg/minecraft-server
```

The ICON is overridden but the MOTD remains `A Minecraft Server Powered by Docker`.

Am I doing something wrong?

**Comment by itzg** [comment]
You're using it right, so I'll look into this.

**Comment by timvisher** [comment]
I've never seen a sed command that looks like this. Usually you would need an `s/…/…` for substitute. Does that actually work?

**Comment by itzg** [comment]
Yeah, I was having some fun with `sed` there :). The c command replaces the entire line that was matched. That way it matches and fixes up even lines that are commented.

**Comment by itzg** [comment]
It works fine for me...but then I tend not to map the `/data` volume myself. If you had a `~/minecraft-data/server.properties` file before running the container, it'll leave your file untouched. 

To test this theory out, stop any minecraft-server containers, move away the contents of your `~/minecraft-data` and then `run` a new container.

Here's the sequence for my test:

    docker run -d -it -p 25568:25565 --name mc20150609 -e 'MOTD=A Different One' -e EULA=TRUE itzg/minecraft-server

and then check the properties' `motd`:

```
$ docker exec mc20150609 cat /data/server.properties|grep motd
motd=A Different One
```

and check in the client:

![image](https://cloud.githubusercontent.com/assets/988985/8072725/b94c1510-0edf-11e5-87e1-fb3c8d6588c0.png)

**Comment by timvisher** [comment]
:facepalm: I can't believe I missed the `-e` conditional there.

What's the purpose of that? It feels like it just makes it a little harder to iterate on getting the container up and running?

**Comment by timvisher** [comment]
> but then I tend not to map the /data volume myself

How do you persist your world data between the container going down and up?

**Comment by itzg** [comment]
Which `-e` conditional do you mean?

As for persisting world data, something that clicked for me later down the road was that Docker containers do always persist their filesystems. In fact...if you do a `docker inspect` on a container it'll reveal the paths, but the main one per container is `/var/lib/docker/containers/<container id>`.

You can always `docker exec -it <container> bash` to get a shell "inside" the container. I use that to install Forge plugins, etc.

**Comment by timvisher** [comment]
> Which `-e` conditional do you mean?

The one where you check if `server.properties` exists. :)

**Comment by timvisher** [comment]
> As for persisting world data, something that clicked for me later down the road was that Docker containers do always persist their filesystems. In fact...if you do a docker inspect on a container it'll reveal the paths, but the main one per container is /var/lib/docker/containers/<container id>.
> 
> You can always docker exec -it <container> bash to get a shell "inside" the container. I use that to install Forge plugins, etc.

Ah. I had no idea. I'm still getting used to docker.

**Comment by timvisher** [comment]
Is there any reason to not update `server.properties` in place every time?

**Comment by itzg** [comment]
My logic was: generate the initial copy using the `-e` environment settings...but after that assume the user has made manual tweaks and avoid blowing them away.

**Comment by itzg** [comment]
...we could add another option to tell it to adjust the properties on every docker `start` or `restart` :)

**Comment by timvisher** [comment]
> ...we could add another option to tell it to adjust the properties on every docker start or restart :)

heh.

![image](https://cloud.githubusercontent.com/assets/34676/8091665/27c2e322-0f83-11e5-8662-43aa0078749e.png)

I think it's fine how it is now.

**Comment by itzg** [comment]
Awesome :)
