### ISSUE TITLE
ONLINE_MODE ignored

### ISSUE THREAD

**Issue by chka** [itzg/dockerfiles#300]
It appears that the ONLINE_MODE is ignored. This is how I run the server:

docker run -d -e ONLINE_MODE=FALSE -p 25565:25565 --name mc itzg/minecraft-server 

Trying to connect, I'm getting the usual [Server thread/INFO]: com.mojang.authlib.GameProfile@2d118453[id=<null>,name=xxxxx,properties={},legacy=false] (/8.8.8.8:44810) lost connection: Disconnected

Any ideas?

**Comment by chka** [comment]
Disregard that... something else on my config messes up with the ONLINE_MODE

**Comment by itzg** [comment]
Thanks for the followup. Yeah, this setting has been working fine for me with a BungeeCord setup.

**Comment by RustyTaco7** [comment]
@chka what did you do to resolve your issue? I am experiencing the same errors you noted.

**Comment by itzg** [comment]
@RustyTaco7 see if this section of the README helps

https://github.com/itzg/docker-minecraft-server/blob/master/README.md#server-configuration

It could be that the server.properties was generated in the data directory when the default value was in use and then if you later change `ONLINE_MODE` to false, then the startup script won't touch server.properties by default.

**Comment by RustyTaco7** [comment]
@itzg that was it thanks a ton! Loving this project!
