### ISSUE TITLE
Not properly working on AWS and DigitalOcean

### ISSUE THREAD

**Issue by ChristianSchneeweiss** [itzg/dockerfiles#303]
I tried this command on my macbook pro
`docker run -it -e EULA=TRUE -e MEMORY=512M -e MAX_PLAYERS=2 -e MAX_WORLD_SIZE=5000 -e VIEW_DISTANCE=5 --memory=512M --cpus=1 -p 25585:25565 --name mc-test-3 itzg/minecraft-server`
and it is working

but on AWS and Digital Ocean servers it is not. I just get this

> usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Apr  5 15:23 /data'
Checking version information.
Checking type information.
Downloading minecraft_server.1.13.2.jar ...
Creating server.properties in /data/server.properties
Setting server-name to 'Dedicated Server' in /data/server.properties
Setting server-port to '25565' in /data/server.properties
Setting motd to 'A Vanilla Minecraft Server powered by Docker' in /data/server.properties
Skip setting allow-nether
Skip setting announce-player-achievements
Skip setting enable-command-block
Skip setting spawn-animals
Skip setting spawn-monsters
Skip setting spawn-npcs
Skip setting generate-structures
Setting view-distance to '5' in /data/server.properties
Skip setting hardcore
Skip setting snooper-enabled
Skip setting max-build-height
Skip setting force-gamemode
Skip setting max-tick-time
Skip setting enable-query
Skip setting query.port
Setting enable-rcon to 'true' in /data/server.properties
Setting rcon.password to 'minecraft' in /data/server.properties
Setting rcon.port to '25575' in /data/server.properties
Setting max-players to '2' in /data/server.properties
Setting max-world-size to '5000' in /data/server.properties
Setting level-name to 'world' in /data/server.properties
Skip setting level-seed
Setting pvp to 'true' in /data/server.properties
Skip setting generator-settings
Setting online-mode to 'true' in /data/server.properties
Skip setting allow-flight
Setting level-type to 'DEFAULT' in /data/server.properties
Setting difficulty to '1' in /data/server.properties
Checking for JSON files.
Copying any mods over...
Setting initial memory to 512M and max to 512M
2019/04/05 15:23:39 Done

**Comment by ChristianSchneeweiss** [comment]
I made another test in a local Ubuntu VM and it did work as well. I used the same command.

Furthermore I tried to run it on Digital Ocean after I created a world on my macbook and transfered it to the Droplet. I mounted it but still had no success

**Comment by itzg** [comment]
Using 512M might be borderline too small; however, I agree it's strange it works fine locally but not on the cloud VMs.

What size/flavor of AWS EC2 instance did you try?

**Comment by ChristianSchneeweiss** [comment]
I kinda solved it already. I think the memory was to small and the instances don't have a swapfile by default. After creating a swap file it worked fine.

I used t2.micro and t3.small

**Comment by itzg** [comment]
Yeah, at one point I know I tried a t2.micro and it was simply too small for a Minecraft server, which is a bummer since I always like minimizing my AWS costs.

I'm going to close the issue since it sounds like it is working "as expected".
