### ISSUE TITLE
Paperspigot does not download correctly for 1.8.8

### ISSUE THREAD

**Issue by itzg** [itzg/dockerfiles#305]
There's an error when trying to use paperspigot on 1.8.8
ERROR: failed to download from https://papermc.io/ci/job/Paper/443/artifact/paperclip.jar (status=0)
the correct url should have a capital "P" in "Paperclip.jar"

reported by @Zinidia

**Comment by Zinidia** [comment]
EULA true
TYPE PAPER
VERSION 1.8.8
PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
LANG C.UTF-8
JAVA_HOME /usr/lib/jvm/java-1.8-openjdk/jre
JAVA_VERSION 8u171
JAVA_ALPINE_VERSION 8.171.11-r0
UID 1000
GID 1000
JVM_XX_OPTS -XX:+UseG1GC
MEMORY 1G
FORGEVERSION RECOMMENDED
SPONGEBRANCH STABLE
LEVEL world
PVP false
DIFFICULTY easy
ENABLE_RCON true
RCON_PORT 25575
RCON_PASSWORD 8Prq7v9t3kYwURZpm
LEVEL_TYPE DEFAULT
SERVER_PORT 25566
ONLINE_MODE FALSE
CONSOLE true
SERVER_NAME Hub Server
REPLACE_ENV_VARIABLES false
ENV_VARIABLE_PREFIX CFG_
WORLD world
PAPER_DOWNLOAD_URL
https://papermc.io/ci/job/Paper/443/artifact/Paperclip.jar
These settings work now

**Comment by itzg** [comment]
I had forgotten about the `PAPER_DOWNLOAD_URL` option; however, I'll have it fix up the URL for the 1.8.8 version.

**Comment by itzg** [comment]
This fix is now available on Docker Hub.
