### ISSUE TITLE
Add nsswitch.conf to Minecraft docker image to fix localhost resolution

### ISSUE THREAD

**Issue by notgne2** [itzg/dockerfiles#307]
There is the related issue here https://github.com/golang/go/issues/22846

`rcon-cli` uses Go, which will resolve `localhost` incorrectly on certain machines, this could be fixed by creating a basic `nsswitch.conf`, `echo 'hosts: files dns' > /etc/nsswitch.conf` should do

**Comment by itzg** [comment]
Is there a particular way you are running the docker container or the daemon that causes that issue for you? I have never encountered `localhost` not resolving within the container.

**Comment by notgne2** [comment]
I think it may depend on the actual network configuration of the network the host machine uses, as unless I am missing something, this issue results in the go DNS resolving skipping resolution using /etc/hosts.

It has had issues on 4 out of 5 CentOS 7 hosts I have tried it on, with identical docker configurations, and have been working around in the meantime by adding `GODEBUG=netdns=cgo` to `env`.

**Comment by itzg** [comment]
I'll work on adding this change sometime today, but I'll need you to verify the fix since I am not able to recreate it and have heard no other reports of this. I was quite confident the addition of `nsswitch.conf` will fix it; however, [this comment](https://github.com/golang/go/issues/22846#issuecomment-433970889) of the issue worries me since the minecraft server image is based on Alpine.

**Comment by itzg** [comment]
This change has been pushed to Docker Hub. @notgne2 , can you see if this resolved the issue for you?

**Comment by notgne2** [comment]
I think that issue is just referring to Alpine being one of the few images lacking `nsswitch.conf` by default and that's why Go are urged to fix it internally, I'll give this a test later today if I get the time.

**Comment by notgne2** [comment]
Tested on one of the problematic servers without the workaround env supplied, no errors in logs and `docker exec -it mc rcon-cli` connects just fine
