### ISSUE TITLE
Chown with certain plugins takes forever and a day

### ISSUE THREAD

**Issue by dali99** [itzg/dockerfiles#309]
My server takes over half an hour to start because of the chown -R on the root directory

```
app_1  | usermod: no changes
app_1  | Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x   11 1000     1000            29 Apr 22 15:13 /data'
app_1  | Checking version information.
app_1  | Checking type information.
app_1  | server.properties already created, skipping
app_1  | Checking for JSON files.
```

This is probably because my plugin folder has a lot of files in them (dynmap tiles)

**Comment by dali99** [comment]
45 minutes last start

**Comment by itzg** [comment]
Hmm, it doesn't seem to be the `chown` since your output doesn't include the log from this statement:

https://github.com/itzg/dockerfiles/blob/master/minecraft-server/start#L15

When is the delay relative to the log lines you provided?

**Comment by dali99** [comment]
Right after the last line

**Comment by itzg** [comment]
Ah, it’s something about the JSON fix process since that last log is “Checking for JSON files”. I’ll look around there.

**Comment by itzg** [comment]
Can you double check that you have `docker pull`ed the latest image? In March I pushed out a fix that limited the JSON fixing logic to only the top-level of the `/data` directory.

If that still doesn't fix it, then I think I'll make that JSON fix a configurable option.

**Comment by dali99** [comment]
I did a docker pull and that does seem to have resolved it!

Apologies!
