### ISSUE TITLE
Copying from /plugins only copy jar files

### ISSUE THREAD

**Issue by kaorun343** [itzg/dockerfiles#310]
Hi.

I'd like to manage plugins' config files with git, so I'd like to put them into /plugins folder with jar files. 

The expected behavior is that the container copy not only jar file but also the other files.
However, the actual behavior is that it only copies jar file, it seems.

Thanks.

**Comment by kaorun343** [comment]
My question is that...

* What is the actual behavior? - which means that only .jar files are copied or all of the files in the plugins folders are copied.
* Is it possible to change the behavior to copy all the files included there if only .jar files are copied?

**Comment by itzg** [comment]
I double checked and yes, as you observed, the script is purposely copying only jar files over. Your scenario makes total sense and I can't think of why it would be a problem to change the behavior to copy all files from `/plugins`.

**Comment by itzg** [comment]
This change is now pushed to Docker Hub.

**Comment by kaorun343** [comment]
Thanks a lot!
