### ISSUE TITLE
How to transfer to another host while preserving state?

### ISSUE THREAD

**Issue by alonsnir** [itzg/dockerfiles#312]
I'm moving the image to another host and have no idea how to preserve all the changes made to the world so far. Could someone please suggest a howto? 
Thanks

**Comment by itzg** [comment]
Good question. I should probably create a wiki page or similar to document some approaches to that.

To help narrow the initial content, are you running the container with the `/data` path attached with a volume? If so, is it a host path volume?

**Comment by alonsnir** [comment]
I'm not familiar with the files layout, but if data is where, well the 'data' is, then it is what i'm after. 
Just to confirm, do I have to copy the entire <code>/data</code>? 
Thanks!

**Comment by alonsnir** [comment]
Copying /data did the trick. Thank you @itzg
