### ISSUE TITLE
Paper docker compose example

### ISSUE THREAD

**Issue by JuniorJPDJ** [itzg/dockerfiles#313]
I'm a little confused how to create it.
As you mentioned paper needs some customizations in `docker run`.
Could you provide example?

**Comment by wojons** [comment]
This is my personal compose file you will need to give a machine a tag to allow it to runminecraft

```version: "3.7"
services:
  
  
  minecraft:
    image: itzg/minecraft-server
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.gameserver_minecraft == true
      resources:
        reservations:
            memory: 6000M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - target: 25565
        published: 25565
        mode: host
    ports:
      - target: 25575
        published: 25575
        mode: host
    volumes:
      - minecraft-volume:/data
    environment:
      EULA: "TRUE"
      VERSION: LATEST
      SERVER_NAME: TEST_MC
      DIFFICULTY: easy
      #OPS: 
      ICON: ""
      MAX_PLAYERS: 50
      MAX_WORLD_SIZE: 10000
      ALLOW_NETHER: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      SNOOPER_ENABLED: "FALSE"
      MAX_BUILD_HEIGHT: 256
      SPAWN_ANIMALS: "TRUE"
      SPAWN_MONSTERS: "TRUE"
      SPAWN_NPCS: "TRUE"
      VIEW_DISTANCE: "TRUE"
      MODE: creative
      PVP: "false"
      SEED: "8678942899319966093"
      
      

volumes:
  minecraft-volume:
    external: true```

**Comment by JuniorJPDJ** [comment]
> This is my personal compose file you will need to give a machine a tag to allow it to runminecraft
> 
> ```
> services:
>   
>   
>   minecraft:
>     image: itzg/minecraft-server
>     deploy:
>       replicas: 1
>       placement:
>         constraints:
>           - node.labels.gameserver_minecraft == true
>       resources:
>         reservations:
>             memory: 6000M
>       restart_policy:
>         condition: on-failure
>         delay: 5s
>         max_attempts: 3
>         window: 120s
>     ports:
>       - target: 25565
>         published: 25565
>         mode: host
>     ports:
>       - target: 25575
>         published: 25575
>         mode: host
>     volumes:
>       - minecraft-volume:/data
>     environment:
>       EULA: "TRUE"
>       VERSION: LATEST
>       SERVER_NAME: TEST_MC
>       DIFFICULTY: easy
>       #OPS: 
>       ICON: ""
>       MAX_PLAYERS: 50
>       MAX_WORLD_SIZE: 10000
>       ALLOW_NETHER: "TRUE"
>       ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
>       SNOOPER_ENABLED: "FALSE"
>       MAX_BUILD_HEIGHT: 256
>       SPAWN_ANIMALS: "TRUE"
>       SPAWN_MONSTERS: "TRUE"
>       SPAWN_NPCS: "TRUE"
>       VIEW_DISTANCE: "TRUE"
>       MODE: creative
>       PVP: "false"
>       SEED: "8678942899319966093"
>       
>       
> 
> volumes:
>   minecraft-volume:
>     external: true```
> ```

I actually needed Paper especially.
In readme there is mentioned that Paper needs special care not to overuse CPU because of console.
There are already working compose examples for other server types in repository.

**Comment by itzg** [comment]
@JuniorJPDJ , let me know if this new example file helps

https://github.com/itzg/dockerfiles/blob/master/minecraft-server/examples/docker-compose-paper.yml

**Comment by JuniorJPDJ** [comment]
@itzg Thank you, I was missing `command: --noconsole`.
It helps ;D
