### ISSUE TITLE
ERROR failed to obtain version manifest URL (6)

### ISSUE THREAD

**Issue by Acem31** [itzg/dockerfiles#317]
Hello
I started with this image today and till the beginning i had one trouble.
It was always the same and i tried a lot of things to fix it.
I'm running docker under synology DSM and the container weren't able to start.
In the log i always get:
`usermod: no changes
Checking version information
curl: (6) Could not resolve host: launchermeta.mojang.com
Checking type information
Downloading minecraft_server..jar ..
curl: (6) Could not resolve host: launchermeta.mojang.com
ERROR failed to obtain version manifest URL (6)
`

I'm not yet familiar with docker but i know a lot of things about network.
I manually set the dns in the run command line and it solved the problem.
 
`docker run -d -it -e EULA=TRUE -p 25565:25565 --dns 8.8.8.8 --name minecraft --privileged itzg/minecraft-server`

So you can close this issue - I hope it will help some one else using Docker for Synology !

**Comment by itzg** [comment]
Thanks for the info.

**Comment by Just-Insane** [comment]
For anyone coming across this from the [helm stable/minecraft](https://github.com/helm/charts/tree/master/stable/minecraft) chart, you can resolve this by editing the deployment spec and setting the following options:

`kubectl edit deployment/minecraft-minecraft`

```
dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
```

**Comment by farhany** [comment]
This issue happens on my K3OS install as well. Above post helped get around it.
