### ISSUE TITLE
Can't start Paper server 1.14.1

### ISSUE THREAD

**Issue by jalu14** [itzg/dockerfiles#326]
Been trying for some hours to switch to Paper as it seems a better performing alternative, but.

`Version LATEST is not supported for PAPER`

This is the output when launching a container with
`-e TYPE=PAPER` 
and either 
`-e VERSION=1.14.1 or -e VERSION=LATEST`

I also set up the download URL to no avail.
`-e PAPER_DOWNLOAD_URL=https://papermc.io/ci/job/Paper-1.14/lastSuccessfulBuild/artifact/paperclip-42.jar`

Vanilla and Spigot versions work or at least I can enter the server, but not with paper, any solution?

**Comment by itzg** [comment]
I was able to launch explicitly passing `VERSION=1.14.1`; however, I just now pushed an update to the image that properly resolved `VERSION=LATEST` to download the specific Paper version.

FWIW, here were the logs even before the updated image:

```
> docker run -it --rm -e EULA=TRUE -e TYPE=PAPER -e VERSION=1.14.1 itzg/minecraft-server
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 May 26 14:08 /data'
Checking version information.
Checking type information.   
Downloading Paper 1.14.1 from https://papermc.io/api/v1/paper/1.14.1/latest/download ...
Skip setting enable-command-block
Skip setting spawn-animals
Skip setting spawn-monsters
Skip setting spawn-npcs
Skip setting generate-structures
Skip setting view-distance
Skip setting hardcore
Skip setting snooper-enabled
Skip setting max-build-height
Skip setting force-gamemode
Skip setting max-tick-time
Skip setting enable-query
Skip setting query.port
Setting enable-rcon to 'true' in /data/server.properties
Setting rcon.password to 'minecraft' in /data/server.properties
Setting rcon.port to '25575' in /data/server.properties
Skip setting max-players
Skip setting max-world-size
Setting level-name to 'world' in /data/server.properties
Skip setting level-seed
Setting pvp to 'true' in /data/server.properties
Skip setting generator-settings
Setting online-mode to 'true' in /data/server.properties
Skip setting allow-flight
Setting level-type to 'DEFAULT' in /data/server.properties
Setting difficulty to '1' in /data/server.properties
Checking for JSON files.
Copying any mods over...
Copying any Bukkit plugins over...
Setting initial memory to 1G and max to 1G
Starting the Minecraft server...
Downloading original jar...
```

**Comment by jalu14** [comment]
I am using portainer to enter env vars, just to point it out. Still I get the same error, trying versions (1.14.1, 1.14.2 and LATEST)
`usermod: no changes


Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx   10 1000     1000          4096 Jun  2 12:37 /data'


Checking version information.


ecking type information.


ERROR: Version 1.14.1 is not supported for PAPER


       Refer to https://papermc.io/ci/


       for supported versions`
May try to launch from console later

**Comment by itzg** [comment]
@jalu14 it looks like you're not running the latest image. Make sure you have `docker pull`ed the latest image since there were recent fixes related to PAPER.

I just now ran the latest successfully with `VERSION=1.14.1`:

```
> docker run -it --rm -e EULA=TRUE -e TYPE=PAPER -e VERSION=1.14.1 itzg/minecraft-server
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Jun  3 02:51 /data'
Checking version information.
Checking type information.
Downloading Paper 1.14.1 from https://papermc.io/api/v1/paper/1.14.1/latest/download ...
Creating server.properties in /data/server.properties
```

**Comment by jalu14** [comment]
Been using aarch64 tag, running on ARM scaleway, image hasn't been updated in a month, I suppose you refer to the latest which does not run on ARM, will have to wait for an update.

**Comment by itzg** [comment]
@jalu14 I have merged the latest changes from master into aarch64 and pushed to Hub if you want to now try that again.

**Comment by jalu14** [comment]
Working wonders on aarch64, thanks for your hard work @itzg
