### ISSUE TITLE
Ram error

### ISSUE THREAD

**Issue by TheYkk** [itzg/dockerfiles#327]
```Setting initial memory to 1G and max to 1G
Starting the Minecraft server...
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1073741824 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /data/hs_err_pid31.log
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 1073741824, 0) failed; error='Out of memory' (errno=12)
2019/05/26 16:56:19 Done
```

run command 
``docker run -d -v ${PWD}:/data     -e TYPE=PAPER -e VERSION=1.14.1     -p 25565:25565 -e EULA=TRUE -e MAX_MEMORY=1G --name maca itzg/minecraft-server``

**Comment by itzg** [comment]
@TheYkk, that sounds like the host system where Docker is running doesn't have 1 GB or so memory available. You can use `top` or `cat /proc/meminfo` to check on your system's memory status.

**Comment by TheYkk** [comment]
i solve problem
system usage ~800mb ram and i increase ram

**Comment by itzg** [comment]
Glad you solved it.
