### ISSUE TITLE
Ubuntu 16 Failes to Download Minecraft Server .jar

### ISSUE THREAD

**Issue by Andrewiski** [itzg/dockerfiles#329]
`sudo docker run -d -it -e ENABLE_QUERY=true -e OPS=DrCDeVries,TBallDeVries,Andrewiski -e ENABLE_RCON=true -e RCON_PASSWORD=devries -v /home/adevries/minecraft/server2:/data -e EULA=TRUE -p 25565:25565 -e VERSION=LATEST --name server2 itzg/minecraft-server`

Server fails to start.

`sudo docker logs -f server2`
Switching to user 'minecraft'
Checking version information.
Checking type information.
Downloading minecraft_server.1.14.2.jar ...
Creating server.properties in /data/server.properties
Setting motd to 'A Minecraft Server Powered by Docker' in /data/server.properties
Skip setting allow-nether
Skip setting announce-player-achievements
Skip setting enable-command-block
Skip setting spawn-animals
Skip setting spawn-monsters
Skip setting spawn-npcs
Skip setting generate-structures
Skip setting view-distance
Skip setting hardcore
Skip setting max-build-height
Skip setting force-gamemode
Skip setting hardmax-tick-timecore
Setting enable-query to 'true' in /data/server.properties
Skip setting query.port
Setting enable-rcon to 'true' in /data/server.properties
Setting rcon.password to 'devries' in /data/server.properties
Setting rcon.port to '25575' in /data/server.properties
Skip setting max-players
Skip setting max-world-size
Setting level-name to 'world' in /data/server.properties
Skip setting level-seed
Setting pvp to 'true' in /data/server.properties
Skip setting generator-settings
Setting online-mode to 'TRUE' in /data/server.properties
Setting level type to DEFAULT
Setting level-type to 'DEFAULT' in /data/server.properties
Setting difficulty to '1' in /data/server.properties
Setting ops
Skipping JSON check. No files present.
Setting initial memory to 1G and max to 1G
Error: Unable to access jarfile minecraft_server.1.14.2.jar

`ls -l`
total 20
drwxr-xr-x 2 adevries adevries 4096 May 31 17:18 config
-rw-r--r-- 1 adevries adevries   65 May 31 17:18 eula.txt
drwxr-xr-x 2 adevries adevries 4096 May 31 17:18 mods
-rw-r--r-- 1 adevries adevries   36 May 31 17:18 ops.txt
-rw-r--r-- 1 adevries adevries  720 May 31 17:18 server.properties

This was an empty folder so it created the files but there is no minecraft_server.1.14.2.jar

```
 wget https://launcher.mojang.com/v1/objects/808be3869e2ca6b62378f9f4b33c946621620019/server.jar
 mv server.jar minecraft_server.1.14.2.jar
sudo docker start server2
```
Seems to fail to down the jar file.  I did a chmod 777 on the folder just in case but it was able to create the other files just not down minecraft server jar file.

**Comment by itzg** [comment]
It looks like you’re running an older copy of the image before I added some better checking of the download status. Can you do a docker pull and see if it still fails for you?

**Comment by Andrewiski** [comment]
I apologize I am green when it comes to docker and didn't know it cached the scripts until you did a pull to get the latest version.  I ran a `sudo docker pull itzg/minecraft-server` and minecraft server jar now downloads correctly.  Thanks again for all your hard work my 13 and 15 year old love being able to run a few simple cli commands to get minecraft running testing mods etc.  Great work.

**Comment by Andrewiski** [comment]
`sudo docker pull itzg/minecraft-server`   

Fixe the issue

**Comment by itzg** [comment]
No problem at all. Yeah, on one hand you’d think that it would keep “latest” up to date but I guess they want to avoid surprises. 

FYI kubernetes layers on a handy feature called “image pull policy” with an “always” option that addresses that.
