### ISSUE TITLE
Question: Timed restarts

### ISSUE THREAD

**Issue by zjael** [itzg/dockerfiles#334]
Any tips or solutions to have timed restarts for server, like being able to restart server daily.
Or maybe even restart when TPS gets low for an extended period of time?

**Comment by itzg** [comment]
Doing a quick search I don't see any elegant ways even with kubernetes. Assuming you have named your container using `--name`, giving it a stable name, you could create a cronjob on your host system that calls `docker restart YOUR_CONTAINER_NAME`.

**Comment by zjael** [comment]
That could work, thanks :)

**Comment by 4ydan** [comment]
any way to have this cronjob inside your image with warning messages to the players before the restart happens, with an env variable to enable this job and how often it runs? can also open a PR for this I think

**Comment by itzg** [comment]
Use an external and/or cron job. I will not accept a PR that adds scheduled restarts **inside** the server container itself.
