### ISSUE TITLE
Jar file not found with space in modpack name

### ISSUE THREAD

**Issue by AlexWerz** [itzg/dockerfiles#340]
I tried to start a "Peace of Mind Server". The resulting ServerStart.sh looks like this:

```
#!/bin/sh
. ./settings-local.sh
java ${JAVA_PARAMETERS} -Xmx${MAX_RAM} -Dfml.queryResult=confirm -Dfml.queryResult=confirm -Dfml.queryResult=confirm -Dfml.queryResult=confirm -Dfml.queryResult=confirm -Dfml.queryResult=confirm -Dfml.queryResult=confirm -Dfml.queryResult=confirm -Dfml.queryResult=confirm -Dfml.queryResult=confirm -jar /data/FeedTheBeast/Peace of Mind Server 2.0.4/forge-1.12.2-14.23.5.2836-universal.jar nogui
``` 

When starting the server I get the following error:
```
Running FTB /data/FeedTheBeast/ServerStart.sh in /data/FeedTheBeast ...
Error: Unable to access jarfile /data/FeedTheBeast/Peace
2019/06/23 08:49:15 Done
```

The problem ist the jar-parameter in the ServerStart.sh:
`-jar /data/FeedTheBeast/Peace of Mind Server 2.0.4/forge-1.12.2-14.23.5.2836-universal.jar`

As the path of the modpack uses spaces the jar parameter needs quotes.

**Comment by itzg** [comment]
You might need to submit issue for the modpack author; however, can you give me a link to that modpack and I'll confirm the issue.

I recently fixed the general support of  FTB/CurseForge to allow for spaces in the path, so this is an issue fresh on my mind:
https://github.com/itzg/dockerfiles/commit/98cec98dd9228865691c520aa66478d7d040dbf0

**Comment by AlexWerz** [comment]
The URL of the modpacks server file is: https://minecraft.curseforge.com/projects/peace-of-mind/files/2712136
I have checked the zip and it does not contain a ServerStart.sh so I assumed it belongs to your code.
To temporarily fix my problem I just added quotes in the ServerStart.sh and it works like it should.

**Comment by itzg** [comment]
OK, I'll close this out, but great to have the original issue documented here for others to find.
