### ISSUE TITLE
elastic search volume /data issue to host

### ISSUE THREAD

**Issue by dhanugupta** [itzg/dockerfiles#42]
Hi

I am trying to use the elastic search docker image with volumised the /data container data to host /data for persistent storage.

something like this:
docker run -d -p 9200:9200 -p 9300:9300  -v /es/data:/data itzg/elasticsearch   
but it throwing issues and docker image getting Exited in few ms. 

if you don't volume its working correctly. but i can't able to persist the data.

Is i am running correct command? or missing something.

**Comment by itzg** [comment]
Yes, that invocation looks correct. The container runs Elasticsearch as uid=1000 by default, so there is likely just a permissions issue.

Can you post the output of `docker logs <your container id or name>`?

**Comment by itzg** [comment]
@dhanugupta , are you still experiencing issues with this or have any more findings?

**Comment by itzg** [comment]
The latest image will only run elasticsearch as an internal, non-root user when launched by default. If run with the `-u=uid` option then an attached `/data` volume can be accessible by the host user with that `uid`. In other words, this latest improvement might help your issue, if it was still occurring.
