### ISSUE TITLE
[es] Cannot install plugin with 2.0

### ISSUE THREAD

**Issue by ajhewett** [itzg/dockerfiles#44]
The cmdline parameters for installing plugins have changed in ES 2.0.
The start script needs to be updated.  i.e.
    `$ES_HOME/bin/plugin install $p`

When trying to install a plugin with the current setup I am seeing errors in the docker logs like:
    `Installing the plugin delete-by-query`
    `ERROR: unknown command [--install]. Use [-h] option to list available commands`

**Comment by itzg** [comment]
Thanks for reporting this. The fixed image is now published to Docker Hub.
