### ISSUE TITLE
Zen discovery doesn't work

### ISSUE THREAD

**Issue by AlexBischof** [itzg/dockerfiles#45]
Hi, 

i have tried to get the multi-node cluster working and have the problem that the nodes are not forming a cluster after
````
http://192.168.99.100:9200/_cluster/health?pretty
````
i get always
```
"number_of_nodes" : 1,
```

I'm using MacOS with *docker-machine*.

Any ideas?

Kind regards
Alex

**Comment by itzg** [comment]
They changed some of the defaults in 2.0, so that might be part of it. For me to try the same scenario are you running one ES node per machine/VM or multiple on one?

**Comment by itzg** [comment]
FYI, confirmed the issue and the root symptom is that the publish host is still loopback:

```
[2015-11-28 16:07:56,464][INFO ][transport                ] [Meteorite II] publish_address {127.0.0.1:9300}, bound_addresses {172.17.0.4:9300}, {[fe80::42:acff:fe11:4]:9300}
```

It looks like I was passing the wrong system property for `network.host`...

**Comment by itzg** [comment]
Getting closer...there was [a configuration change](https://www.elastic.co/guide/en/elasticsearch/guide/current/_important_configuration_changes.html#_prefer_unicast_over_multicast)

**Comment by itzg** [comment]
Built and pushed new image `539cf207a380`
