### ISSUE TITLE
unable to execute /start-minecraft: Text file busy?

### ISSUE THREAD

**Issue by everett-toews** [itzg/dockerfiles#47]
When running the latest itzg/minecraft-server image (Image ID: 61f744a5eaa6) on VirtualBox, I get the following error.

```bash
$ docker images itzg/minecraft-server
REPOSITORY              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
itzg/minecraft-server   latest              61f744a5eaa6        2 hours ago         399.3 MB

$ docker run --detach --interactive --tty \
>   --name minecraft-whitelist \
>   -e VERSION=LATEST \
>   -e OPS=user1 \
>   -e WHITELIST=user1,user2,user3,user4 \
>   -e EULA=TRUE \
>   -e MOTD="VirtualBox World" \
>   -p 25565:25565 \
>   itzg/minecraft-server
e997fef2bb9b684e1220eeff716d1277255082f56363170fdefdf110da843b05

$ docker ps -a
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS                      PORTS               NAMES
e997fef2bb9b        itzg/minecraft-server   "/start"            14 seconds ago      Exited (1) 14 seconds ago                       minecraft-whitelist

$ docker logs minecraft-whitelist
usermod: no changes
sudo: unable to execute /start-minecraft: Text file busy
```

However if I run it in another environment, such as [Carina](https://getcarina.com/). It works.

```bash
$ docker images itzg/minecraft-server
REPOSITORY              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
itzg/minecraft-server   latest              61f744a5eaa6        2 hours ago         399.3 MB

$ docker run --detach --interactive --tty \
>   --name minecraft-whitelist \
>   -e VERSION=LATEST \
>   -e OPS=user1 \
>   -e WHITELIST=user1,user2,user3,user4 \
>   -e EULA=TRUE \
>   -e MOTD="Carina World" \
>   -p 25565:25565 \
>   itzg/minecraft-server
8aaf17d6bd83c101c3e8ac6989de95247df59049df02e244e5e92041643ce64d

$ docker ps
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS                           NAMES
8aaf17d6bd83        itzg/minecraft-server   "/start"            28 seconds ago      Up 27 seconds       xxx.xxx.xxx.xxx:25565->25565/tcp   0dc4a907-960c-4c1b-9f07-cd9071fb87b1-n1/minecraft-whitelist

$ docker attach minecraft-whitelist
/whitelist list
[17:44:59] [Server thread/INFO]: There are 4 (out of 0 seen) whitelisted players:
[17:44:59] [Server thread/INFO]: user1, user2, user3 and user4
```

@itzg Can you please try it locally/VirtualBox?

I'd hate to think I borked your image with https://github.com/itzg/dockerfiles/pull/46. If it works for you, feel free to just close this.

**Comment by itzg** [comment]
Yep, I'll try in Linux and Windows (VirtualBox) and see what it does for me. It's very unlikely to be our last round of changes unless I did something to line endings on commit.

**Comment by itzg** [comment]
...and thanks for the pointer to Carina. I've been on the lookout for good container hosting.

**Comment by itzg** [comment]
Test 1, success, Ubuntu 15.10, local

```
 $ docker version                                                                                            [12:53:50]
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:39:44 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:39:44 UTC 2015
 OS/Arch:      linux/amd64

 $ docker images itzg/minecraft-server                                                                       [12:53:44]
REPOSITORY              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
itzg/minecraft-server   latest              61f744a5eaa6        3 hours ago         399.3 MB
```

**Comment by itzg** [comment]
...and success with tests 2, Windows/VirtualBox, and 3, Carina. Carina is super nice BTW. My son and I got up and running in just a few minutes.

Try exploring a "temp/disposable" instance using:

    docker run --rm -it -p 25565:25565 itzg/minecraft-server bash

and then confirm the presence and access to `/start` and `/start-minecraft`. From there you could try running starting from there with

    EULA=TRUE /start-minecraft

**Comment by itzg** [comment]
Hold the phone, I just now hit this once during several runs on Windows/VirtualBox. I'm thinking about introducing a re-try loop in `/start`...

**Comment by everett-toews** [comment]
Alright. Let me know how it goes. I'm happy to do some testing.

**Comment by itzg** [comment]
I introduced an `lsof` check in the branch https://github.com/itzg/dockerfiles/tree/mc-issue-47 and so far I haven't seen the issue. Can you test that out too?

**Comment by everett-toews** [comment]
Just tried it. 

Somehow the whitelist stuff disappeared from https://github.com/itzg/dockerfiles/blob/mc-issue-47/minecraft-server/start-minecraft.sh

**Comment by itzg** [comment]
Oops, apparently I hadn't pulled the latest master. Now I have merged and pushed the branch with the latest.

**Comment by everett-toews** [comment]
:+1: 

I tried the new image and it worked both locally and on Carina. Thanks!

**Comment by itzg** [comment]
Thanks. It's now merged and pushed https://hub.docker.com/r/itzg/minecraft-server/builds/bq4ub7hnwtkptmbrvgadk5/
