### ISSUE TITLE
[mc] Allow given WORLD URLs to not end in .zip

### ISSUE THREAD

**Issue by itzg** [itzg/dockerfiles#50]
@sshipway I was testing out my addition of `WORLD` to my container-deployer web app and noticed that download links from http://www.minecraftmaps.com/ are exposed as something like http://www.minecraftmaps.com/parkour-maps/aspect-parkour/download but then do a temp redirect to the actual zip's URL.

Since `wget` can follow redirects, perhaps we should let it download and then verify the final the filename/content.

**Comment by itzg** [comment]
In this particular case they're using several layers of redirection including a `<script>` snippet to pull down mediafire content. They're obviously trying to block programmatic downloading, so we'll assume our end user has posted the zip somewhere readily accessible.

**Comment by sshipway** [comment]
Good point; the script will catch non-zip files when trying to unpack after downloading in any case, and so it cannot overwrite things it shouldn't.  Maybe the wget call should set the Accept header so that only the correct MIME type (application/zip or octet-stream) is accepted?

**Comment by itzg** [comment]
It actually inspired me to add file upload support in the web app I'm developing. I should have a test instance deployed for you to try out soon.

**Comment by itzg** [comment]
...and here's that source code, @sshipway :

https://github.com/itzg/minecraft-container-yard

Happy Holidays :)
