### ISSUE TITLE
Upgrade to latest (but legacy) ES releases 1.x, 2.1.x

### ISSUE THREAD

**Issue by itzg** [itzg/dockerfiles#59]

**Comment by quorak** [comment]
hey @itzg, great es script. it works like a charm. is there a reason that you use these old es versions? would be great to have latest running. eg 5-alpha  ;)

**Comment by itzg** [comment]
FYI, I have opened #108 to track adding the 5.0 RC release as an image.

**Comment by itzg** [comment]
Added 

- https://github.com/itzg/dockerfiles/tree/es-2.2.0
- https://github.com/itzg/dockerfiles/tree/es-2.3.4
- https://github.com/itzg/dockerfiles/tree/es-2.4.3
