### ISSUE TITLE
minecraft-server not downloading Spigot 1.9

### ISSUE THREAD

**Issue by miles** [itzg/dockerfiles#62]
Spigot 1.9 is available. I haven't had a chance to dive into this, but a quick scan of the start-minecraft.sh I think the URL may have changed. I was able to manually download Spigot-1.9 from http://getspigot.org/jenkins/job/Spigot/lastSuccessfulBuild/artifact/spigot-1.9.jar

**Comment by itzg** [comment]
Ah yes, the `spigot18` bit in the URL path will probably interfere with 1.9. I'll take a look later when I'm off a corporate LAN, but you're also welcome to submit a PR...if so, see if there's a `spigot19` directory to make it more deterministic than the Jenkins link.

**Comment by itzg** [comment]
This is now pushed to hub, so do a `docker pull itzg/minecraft-server` and you should be good to go.

**Comment by miles** [comment]
Thank you! I'm new to github and development in general, so when you said submit a PR, I knew you meant a Pull Request, but I didn't know how to submit one :/

I'd like to help your project in some way. Is there a place where you chat about it or have some sort of TODO list?

**Comment by itzg** [comment]
Awesome and I'd be glad to help get you up to speed. Here's a Gitter chat area for `dockerfiles`

[![Gitter](https://badges.gitter.im/itzg/dockerfiles.svg)](https://gitter.im/itzg/dockerfiles?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

and over here there's a couple people helping out on a web app to create a Minecraft server containers "as a service" (aka [MCCY](https://github.com/moorkop/mccy-engine)):

[![Gitter](https://badges.gitter.im/moorkop/mccy-engine.svg)](https://gitter.im/moorkop/mccy-engine?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

We're also trying out [Slack ](https://moorkop.slack.com) if you're more used to that.

**Comment by itzg** [comment]
...and yep, you're spot on: PR = pull request
