### ISSUE TITLE
TYPE=BUKKIT broken without building source

### ISSUE THREAD

**Issue by tedgaunt** [itzg/dockerfiles#71]
TYPE=BUKKIT is broken, unless building source.  fails to map to correct URL to get spigot server jar

**Comment by itzg** [comment]
About 20 minutes ago I pushed a new image to Hub with ID `sha256:b7774308fa74c714e2e2f3e258f4b5702c916a04a0036b372386b1c0664b0434`.

I just now tried these two scenarios and they are now (but weren't before the latest fix) working as I'd expect:

```
 $ docker run --rm -it -e EULA=TRUE -e TYPE=BUKKIT itzg/minecraft-server
usermod: no changes
Switching to user 'minecraft'
Checking version information.
Checking type information.
Downloading Craftbukkit 1.9.2
```

and then to grab Spigot specifically:

```
 $ docker run --rm -it -e EULA=TRUE -e TYPE=SPIGOT itzg/minecraft-server
usermod: no changes
Switching to user 'minecraft'
Checking version information.
Checking type information.
Downloading Spigot 1.9.2
```

Please double check with the latest image, but let me know if you're still experiencing problems with that one.

**Comment by tedgaunt** [comment]
That fixed it.  Thanks!
