### ISSUE TITLE
cannot stop/start or restart container if /data volume is mounted

### ISSUE THREAD

**Issue by tedgaunt** [itzg/dockerfiles#72]
I happen to be running with TYPE=BUKKIT, but this probably happens with other types as well.

I'm mounting /data volume.   I expect to be able to stop the container, and start the container.  However, the subsequent start container causes

usermod: no changes
mkdir: cannot create directory '/home/minecraft': File exists.

As a workaround, I found that I can "clear" the container, and then the start command will work again.

obviously I'm trying to not loose my data directory, and the resulting customizations...

**Comment by Farigh** [comment]
Same here, consider using this instead, that solved the problem for me :
`mkdir -p /home/minecraft `

**Comment by itzg** [comment]
Thanks @Farigh , a -p is exactly what I need there.

**Comment by itzg** [comment]
Pushed the fix to Hub at image ID `sha256:80773aee87afe6dbf5bb2ee510273aa775da2633ae4db40292e8b44da0545780`

**Comment by tedgaunt** [comment]
Thanks man.  Looking good.

Thanks for your service on this container.  It has been really helpful to
quickly run minecraft for my kids.  Much easier doing it this way, than
having to fiddle with everything manually each time.

**Comment by itzg** [comment]
You're very welcome @tedgaunt . Since your "customers" are your kids :), you'll relate to this article I wrote for Carina https://getcarina.com/blog/deploying-and-building-minecraft-as-a-service/

**Comment by tedgaunt** [comment]
Thanks for the pointer.  Reading your article now and signing up on Carina.

**Comment by tedgaunt** [comment]
Very interesting.  I spent a few minutes trying the mccy source, but it
failed to build through mvn ... I didn't look into why.

very curious as to what the mincraft container yard looks like.  Is there a
demo logon, or is that private?

**Comment by itzg** [comment]
Yes, there's a test instance at

https://mccy-staging.itzg.me/

and if you arrow over to the login screen, the login is mccy/testing

As for the maven error, feel free to send me any snippets and I'll see what
it's doing. I also need to circle back with some Docker-ish instructions
for building within a container.
