### ISSUE TITLE
java called twice

### ISSUE THREAD

**Issue by Farigh** [itzg/dockerfiles#76]
I don't know if there are any reason for that but I noticed you ran the java process twice in start-minecraft.sh : 

```shell
# If we have a bootstrap.txt file... feed that in to the server stdin
if [ -f /data/bootstrap.txt ];
then
     exec java $JVM_OPTS -jar $SERVER < /data/bootstrap.txt
else
     exec java $JVM_OPTS -jar $SERVER
fi

# This call could be removed 
exec java $JVM_OPTS -jar $SERVER
```
First in the if/else part and then after it a second time. 
I've been adding a pipe to easilly communicate with the server and removed the last call through [this patch](https://github.com/Farigh/minecraft-server-utils/blob/master/.utils/docker-diff/start-minecraft.patch) and it doesn't seem to be a problem.

**Comment by itzg** [comment]
Oh yeah, that's a definitely a typo, but it never executes that line since the exec swaps in the Java process from that point forward.

**Comment by Farigh** [comment]
My bad I'm piping to exec that's why I did get there.
Still dead code :)
