### ISSUE TITLE
TYPE=spigot broken - getspigot seems to be toast

### ISSUE THREAD

**Issue by bnaylor** [itzg/dockerfiles#77]
This fails:

  curl -o /tmp/versions -sSL https://getspigot.org/api/getversions

Looks like that domain is redirecting to mcadmin.net now, and the certs are wrong and the url is a 404 as well.

**Comment by itzg** [comment]
Hmm, I wonder if they were "asked" to change their site name to avoid confusion with Spigot itself.

I'll have to investigate a little more since they didn't seem to transplant the `/api/getversions` call as it was before.

**Comment by itzg** [comment]
@bnaylor , as a workaround you can add `-e BUILD_FROM_SOURCE=true`...

**Comment by itzg** [comment]
@bnaylor , can you try out the latest image to confirm the fix works for you too?

The image ID is sha256:a68fe49cc24e433883c242ac4e69b4ba1b7a2508b9e3f810b95cf35ecbf37240

**Comment by bnaylor** [comment]
Works now -- thanks!
