### ISSUE TITLE
Minecraft: Clean shutdown?

### ISSUE THREAD

**Issue by jbeda** [itzg/dockerfiles#81]
Feature request

It turns out that Minecraft doesn't save state on shutdown.  You have to inject a `/stop` command into the console.

This has been done by others with screen and pushing input form a script.

Also might be possible using rcon but I don't see an obvious packaged client there.

I'd consider doing this with a bash shutdown hook. We'd want to stop `exec`ing java and just make it a regular old sub-process.

**Comment by itzg** [comment]
Hmm, it seems like the SIGTERM used to close out the server process gracefully, but maybe that behavior isn't consistent across versions. I'll investigate something, especially in the realm of `rcon`...might have to put together a little java app for that.

**Comment by Kianda** [comment]
Tried this sending a command to the docker attach with this

echo 'help' | docker attach mc

but as response i get:
"the input device is not a TTY"

So there is still no way to stop the server saving the world correctly?

Thanks

**Comment by jbeda** [comment]
I guessing that the best way to do this would be via rcon.  This seems like a useful tool: https://github.com/Kealper/Batchcraft

**Comment by itzg** [comment]
Good find, @jbeda . With the [ENABLE_RCON](https://github.com/itzg/dockerfiles/tree/master/minecraft-server#rcon) the combination of these two would be the most robust solution.

**Comment by AragurDEV** [comment]
Any update on this topic?  
Is stopping the container enough I do I have to manually inject a stop command via RCON?

**Comment by AragurDEV** [comment]
Okay I found the answer by myself: https://github.com/itzg/dockerfiles/issues/232#issuecomment-406623199
So I think this issue can be closed?

**Comment by itzg** [comment]
Thanks @AragurDEV, I had forgotten to circle around to this issue after adding https://github.com/itzg/mc-server-runner to catch the signal and gracefully convey the stop command to the MC java process.
