### ISSUE TITLE
Minecraft: enhancement - new functionality being provided in the new versions.json

### ISSUE THREAD

**Issue by NetworkEng** [itzg/dockerfiles#84]
Digging around in the new versions.json file, there are now version / release specific URL's included, pointing to release specific JSON files.  e.g., check the outputs for the following two commands:

`curl -sSL https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r '.versions'`

`curl -sSL https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r '.versions[0].url'`

Check out all of the new data within the json file referenced in that URL, which is currently:
[https://launchermeta.mojang.com/mc/game/281697b6f88d757066b5f0427b40ffabc50e79b9/1.10.json](url)

Enjoy the rabbit hole you'll inevitably find yourself in as a result. :)

**Comment by itzg** [comment]
I noticed the new json file had a new cross-reference, but hadn't poked into one of those. Now that I'm looking, I wonder this is primarily info used by the launcher; however, keep me posted here as you find any specific goodies in there.

**Comment by NetworkEng** [comment]
The version / release specific json file urls within versions.json contain some pretty significant information in regards to where the server jar files will likely be maintained in the near future.  Note that they are not pointing to AWS.  :)

I think this is significant for two reasons. One, they are already planning to deprecate the location of versions.json, moving it to launcher.mojang.com, and two, Microsoft owns Mojang, and Amazon AWS is a direct competitor to their Azure cloud solution.  I imagine that they will probably be ditching AWS pretty soon for hosting .jar files.

Additionally, the json file referenced in the versions.json file not only includes the download URL for the server jar file, it also includes a sha1 hash of the file for validating the download (and much, much more).

E.g.:
Latest server .jar file URL:
`curl -sSL $(curl -sSL https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r '.versions[0].url') | jq -r '.downloads.server.url'`

Latest server .jar file sha1 hash:
`curl -sSL $(curl -sSL https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r '.versions[0].url') | jq -r '.downloads.server.sha1'`

If you haven't had a chance yet to look at all of the data in the json url in my original message, it's well worth checking out.

**Comment by NetworkEng** [comment]
Well, now that I have dug a bit deeper into the whois record for launcher.mojang.com, (for me) it's pointing to a server under cloudfront.net, which is Amazon.  That said, I think it may be best to future proof getting the server download URL in a manner similar to what I showed above.  I'd still bet that they could move off of the old AWS URL in the future.  Probably the main thing that's holding them back is all of the hard coded scripts in the community that are currently pointing to the AWS URL.

**Comment by itzg** [comment]
Agreed, these do seem to be signs that they would do the logical thing and move off their competitor's CDN. Regardless, you bring up a good point that the definitive jar URL is conveyed in that metadata. I'll replace the path derivation with the metadata...or you're welcome to submit a pull request.

**Comment by NetworkEng** [comment]
Haven't used jq before now, so here's my attempt at trying to create some bash + jq that will (hopefully without much doubt) get the info that's required.

One thing I don't like about the new versions json file, is that it has all of the versions as a list of elements.  To be sure were getting the latest release, one should probably validate using slightly more complex jq syntax.  E.g.:

    launcher_json=$(curl -sSL https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r '.latest.release as $current | .versions[] | select(.id == $current and .type == "release") | .url')

The jq syntax first assigns the latest release version number to a variable $current, then passes the .versions list to the select function, which will return only the dictionary element in the list that has the $current version number, and the type is "release", and from that result it returns the URL of the launcher JSON file that we want.  It's probably overkill in comparison to my previous examples, but I hate assuming that the first element in the list will always contain the latest release.

Here's one suggestion for an updated installVanilla function: [http://dpaste.com/293C19A](http://dpaste.com/293C19A)

Note that though I've added the SERVER_SHA1 variable, I'm not sure whether your docker image has the sha1sum command (think it's installed via coreutils, so probably ok), and, I'm not sure how you'd want to handle either a wget failure or a mismatch of the sha1 hash.  I'm assuming that the container should fail to install, but since there is currently no checking for a failed server file download in the start_minecraft.sh script, I left it unfinished and commented out in the linked example.

**Comment by itzg** [comment]
Sorry for the delay. I'll work on getting this into the image tonight. I'm still trying to get a grip on jq, so you're variable usage was quite informative. Thanks.

**Comment by itzg** [comment]
Fixed in 08ba4717108d0d43c662c5b8b7e3304e7752489b
