### ISSUE TITLE
minecraft-server: /tmp/mcadmin-versions.db Is out of Date

### ISSUE THREAD

**Issue by DeedleFake** [itzg/dockerfiles#87]
For example, Spigot 1.10.2 is available, but the `start-minecraft` script refuses to download it because it doesn't think it exists. It won't even run it if I download it manually.

**Comment by itzg** [comment]
@DeedleFake , the latest image build with `sha256:f8c362e2f5849ac2651e2062d722609f07d13982aa01e5d91e12d0b861c2a727` seems to have fixed this; however, I am also going to switch over to using the [restify](https://github.com/itzg/restify) tool that I wrote to compute available versions at runtime.
