### ISSUE TITLE
latest container build doesn't respect ES_HEAP_SIZE

### ISSUE THREAD

**Issue by jaychris** [itzg/dockerfiles#93]
passing in "-e ES_HEAP_SIZE=<something>" is no longer picked up.  No matter the setting, ES always starts with the default 1G heap size.

**Comment by jaychris** [comment]
I think the issue is that  you are executing su like "su -c "$CMD" - elasticsearch", which does not inherit root's environment (including the ES_HEAP_SIZE).  I think the right fix is to remove the "-", like:

su - c "$CMD" elasticsearch

**Comment by jaychris** [comment]
I worked around the issue by building a local container hosted on my private registry.  When the fixes are validated/checked in, I'll switch back to the public copy... :-)

**Comment by itzg** [comment]
Thanks for digging into both of these issues. You're very welcome to submit a PR since you have a local solution.

**Comment by jaychris** [comment]
fixed at sha256:99f265f5a774e3120d1a311e1bb42983137a180b283ce0a90a6b379eb04caa8f

**Comment by itzg** [comment]
Fixed by 87b2ce1c2466e209bc78876b5513aa270e24a852
